-- 加入全功能NPC
CREATE TABLE IF NOT EXISTS `custom_npc` (
  `id` mediumint(7) unsigned NOT NULL DEFAULT '0',
  `idTemplate` smallint(5) unsigned NOT NULL DEFAULT '0',
  `name` varchar(200) CHARACTER SET utf8 NOT NULL,
  `serverSideName` tinyint(1) NOT NULL DEFAULT '1',
  `title` varchar(45) CHARACTER SET utf8 NOT NULL,
  `serverSideTitle` tinyint(1) NOT NULL DEFAULT '1',
  `class` varchar(200) DEFAULT NULL,
  `collision_radius` decimal(6,2) DEFAULT NULL,
  `collision_height` decimal(6,2) DEFAULT NULL,
  `level` tinyint(2) DEFAULT NULL,
  `sex` enum('etc','female','male') NOT NULL DEFAULT 'etc',
  `type` varchar(22) DEFAULT NULL,
  `attackrange` smallint(4) DEFAULT NULL,
  `hp` decimal(8,0) DEFAULT NULL,
  `mp` decimal(6,0) DEFAULT NULL,
  `hpreg` decimal(10,4) DEFAULT NULL,
  `mpreg` decimal(10,4) DEFAULT NULL,
  `str` tinyint(2) NOT NULL DEFAULT '40',
  `con` tinyint(2) NOT NULL DEFAULT '43',
  `dex` tinyint(2) NOT NULL DEFAULT '30',
  `int` tinyint(2) NOT NULL DEFAULT '21',
  `wit` tinyint(2) NOT NULL DEFAULT '20',
  `men` tinyint(2) NOT NULL DEFAULT '20',
  `exp` int(9) NOT NULL DEFAULT '0',
  `sp` int(9) NOT NULL DEFAULT '0',
  `patk` mediumint(6) DEFAULT NULL,
  `pdef` mediumint(6) DEFAULT NULL,
  `matk` mediumint(6) DEFAULT NULL,
  `mdef` mediumint(6) DEFAULT NULL,
  `atkspd` smallint(4) NOT NULL DEFAULT '230',
  `critical` tinyint(1) NOT NULL DEFAULT '1',
  `aggro` smallint(4) NOT NULL DEFAULT '0',
  `matkspd` smallint(4) NOT NULL DEFAULT '333',
  `rhand` decimal(5,0) DEFAULT NULL,
  `lhand` decimal(5,0) DEFAULT NULL,
  `enchant` tinyint(1) NOT NULL DEFAULT '0',
  `walkspd` smallint(3) NOT NULL DEFAULT '60',
  `runspd` smallint(3) NOT NULL DEFAULT '120',
  `targetable` tinyint(1) NOT NULL DEFAULT '1',
  `show_name` tinyint(1) NOT NULL DEFAULT '1',
  `dropHerbGroup` tinyint(1) NOT NULL DEFAULT '0',
  `basestats` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

REPLACE INTO `custom_npc` VALUES (88000,32365,'Snow',0,'Event Manager',0,'LineageNPC2.TP_game_staff',5.00,12.50,70,'male','L2Merchant',40,2444,1225,0.00,0.00,40,43,30,21,20,20,0,0,1086,471,749,313,230,1,0,333,0,0,0,68,109,1,1,0,0);
