ALTER TABLE `clan_introductions`  DEFAULT CHARSET=utf8;
ALTER TABLE `comments`  DEFAULT CHARSET=utf8;
ALTER TABLE `forums`  DEFAULT CHARSET=utf8;
ALTER TABLE `registered_gameservers` DEFAULT CHARSET=utf8;
ALTER TABLE `posts`  DEFAULT CHARSET=utf8;
ALTER TABLE `topics`  DEFAULT CHARSET=utf8;