/************ Made in Taiwan ************/

/***** 貳幕繽炫風 11-11 *****/ 
/***** castlename-tw *****/ 
/***** auction.sql *****/
UPDATE `auction` SET `itemName` = '月長石廳' WHERE `itemId` = 22;
UPDATE `auction` SET `itemName` = '瑪瑙廳' WHERE `itemId` = 23;
UPDATE `auction` SET `itemName` = '黃玉廳' WHERE `itemId` = 24;
UPDATE `auction` SET `itemName` = '紅寶石廳' WHERE `itemId` = 25;
UPDATE `auction` SET `itemName` = '水晶廳' WHERE `itemId` = 26;
UPDATE `auction` SET `itemName` = '瑪瑙廳' WHERE `itemId` = 27;
UPDATE `auction` SET `itemName` = '藍寶石廳' WHERE `itemId` = 28;
UPDATE `auction` SET `itemName` = '月長石廳' WHERE `itemId` = 29;
UPDATE `auction` SET `itemName` = '綠寶石廳' WHERE `itemId` = 30;
UPDATE `auction` SET `itemName` = '黑之公館' WHERE `itemId` = 31;
UPDATE `auction` SET `itemName` = '紅之公館' WHERE `itemId` = 32;
UPDATE `auction` SET `itemName` = '綠之公館' WHERE `itemId` = 33;
UPDATE `auction` SET `itemName` = '黃金接待室' WHERE `itemId` = 36;
UPDATE `auction` SET `itemName` = '白銀接待室' WHERE `itemId` = 37;
UPDATE `auction` SET `itemName` = '米索莉接待室' WHERE `itemId` = 38;
UPDATE `auction` SET `itemName` = '銀色小屋' WHERE `itemId` = 39;
UPDATE `auction` SET `itemName` = '黃金小屋' WHERE `itemId` = 40;
UPDATE `auction` SET `itemName` = '青銅接待室' WHERE `itemId` = 41;
UPDATE `auction` SET `itemName` = '黃金接待室' WHERE `itemId` = 42;
UPDATE `auction` SET `itemName` = '白銀接待室' WHERE `itemId` = 43;
UPDATE `auction` SET `itemName` = '米索莉接待室' WHERE `itemId` = 44;
UPDATE `auction` SET `itemName` = '青銅接待室' WHERE `itemId` = 45;
UPDATE `auction` SET `itemName` = '銀色小屋' WHERE `itemId` = 46;
UPDATE `auction` SET `itemName` = '月長石廳' WHERE `itemId` = 47;
UPDATE `auction` SET `itemName` = '瑪瑙廳' WHERE `itemId` = 48;
UPDATE `auction` SET `itemName` = '綠寶石廳' WHERE `itemId` = 49;
UPDATE `auction` SET `itemName` = '藍寶石廳' WHERE `itemId` = 50;
UPDATE `auction` SET `itemName` = '蒙特接待室' WHERE `itemId` = 51;
UPDATE `auction` SET `itemName` = '修特倫接待室' WHERE `itemId` = 52;
UPDATE `auction` SET `itemName` = '維納斯接待室' WHERE `itemId` = 53;
UPDATE `auction` SET `itemName` = '瑪爾斯接待室' WHERE `itemId` = 54;
UPDATE `auction` SET `itemName` = '雅蒂斯接待室' WHERE `itemId` = 55;
UPDATE `auction` SET `itemName` = '普魯托接待室' WHERE `itemId` = 56;
UPDATE `auction` SET `itemName` = '特拉潘接待室' WHERE `itemId` = 57;
UPDATE `auction` SET `itemName` = '鋼鐵之廳' WHERE `itemId` = 58;
UPDATE `auction` SET `itemName` = '冷鑄之廳' WHERE `itemId` = 59;
UPDATE `auction` SET `itemName` = '熱煉之廳' WHERE `itemId` = 60;
UPDATE `auction` SET `itemName` = '鈦金之廳' WHERE `itemId` = 61;

/***** GAME *****/ 
/***** auto_chat_text.sql *****/
UPDATE `auto_chat_text` SET `chatText` = '%player_cabal_loser%！大家等著絕望吧！死亡女神即將要降臨了！' WHERE `chatText` = '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!';
UPDATE `auto_chat_text` SET `chatText` = '%player_cabal_loser%！你已經遭遇不幸！' WHERE `chatText` = '%player_cabal_loser%! You bring an ill wind!';
UPDATE `auto_chat_text` SET `chatText` = '%player_cabal_loser%！還不如快點放棄！' WHERE `chatText` = '%player_cabal_loser%! You might as well give up!';
UPDATE `auto_chat_text` SET `chatText` = '失敗者將遭受詛咒！' WHERE `chatText` = 'A curse upon you!';
UPDATE `auto_chat_text` SET `chatText` = '大家等著絕望吧！死亡女神即將要降臨了！' WHERE `chatText` = 'All is lost! Prepare to meet the goddess of death!';
UPDATE `auto_chat_text` SET `chatText` = '大家等著絕望吧！滅亡的預言即將就要實現了！' WHERE `chatText` = 'All is lost! The prophecy of destruction has been fulfilled!';
UPDATE `auto_chat_text` SET `chatText` = '聆聽滅亡的預言吧！末日時代即將要來臨了！' WHERE `chatText` = 'The prophecy of doom has awoken!';
UPDATE `auto_chat_text` SET `chatText` = '這個世界即將滅亡！' WHERE `chatText` = 'This world will soon be annihilated!';
UPDATE `auto_chat_text` SET `chatText` = '%player_cabal_winner%！施予你啟示的祝福！' WHERE `chatText` = '%player_cabal_winner%! I bestow on you the authority of the abyss!';
UPDATE `auto_chat_text` SET `chatText` = '%player_cabal_winner%！黑暗將會被放逐！' WHERE `chatText` = '%player_cabal_winner%, Darkness shall be banished forever!';
UPDATE `auto_chat_text` SET `chatText` = '%player_cabal_winner%！榮耀時刻就在眼前！' WHERE `chatText` = '%player_cabal_winner%, the time for glory is at hand!';
UPDATE `auto_chat_text` SET `chatText` = '迎接勝利的到來吧！' WHERE `chatText` = 'All hail the eternal twilight!';
UPDATE `auto_chat_text` SET `chatText` = '聆聽黑暗的啟示吧！混沌的時代已經開始了！' WHERE `chatText` = 'As foretold in the prophecy of darkness, the era of chaos has begun!';
UPDATE `auto_chat_text` SET `chatText` = '審判的日子即將來臨！' WHERE `chatText` = 'The day of judgment is near!';
UPDATE `auto_chat_text` SET `chatText` = '聆聽黑暗的啟示吧！死亡的樂園即將來臨了！' WHERE `chatText` = 'The prophecy of darkness has been fulfilled!';
UPDATE `auto_chat_text` SET `chatText` = '聆聽黑暗的啟示吧！沉睡中的黑暗甦醒了！' WHERE `chatText` = 'The prophecy of darkness has come to pass!';

/***** staticobject-tw *****/ 
/***** castle_door.sql *****/
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '19210001' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '19210002' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '19210003' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '19210004' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '19210005' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '19210006' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '19210007' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '19210008' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '19210009' AND `castleId` = 1;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '20220001' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '20220002' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '20220003' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '20220004' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '20220005' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '20220006' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '20220007' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '20220008' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '20220009' AND `castleId` = 2;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '23220001' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '23220002' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '23220003' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '23220004' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '23220005' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '23220006' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '23220007' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '23220008' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '23220009' AND `castleId` = 3;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '22190001' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '22190002' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '22190003' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '22190004' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '22190005' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '22190006' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22190007' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22190008' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22190009' AND `castleId` = 4;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '24180001' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '24180002' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '內城牆' WHERE `id` = '24180003' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '大廳門' WHERE `id` = '24180004' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '大廳門' WHERE `id` = '24180005' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '24180006' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180007' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180008' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180009' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180010' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '24180011' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24180012' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24180013' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24180014' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24180015' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180016' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180018' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180019' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180020' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24180021' AND `castleId` = 5;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '23250001' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '23250002' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '23250003' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '23250004' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '23250005' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '23250006' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '23250007' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '23250008' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '23250009' AND `castleId` = 6;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '24160009' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '24160010' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24160011' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24160012' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24160013' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '24160014' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160015' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160016' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160017' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160018' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160019' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160020' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '24160021' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '24160022' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '24160023' AND `castleId` = 7;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '20160001' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '20160002' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '20160003' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '20160004' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '20160005' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '20160006' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '20160007' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '20160008' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '20160009' AND `castleId` = 8;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '22130001' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '外城門' WHERE `id` = '22130002' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130003' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '22130004' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '城牆' WHERE `id` = '22130005' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '22130006' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '22130007' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '22130008' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '內城門' WHERE `id` = '22130009' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130010' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130011' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130012' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130013' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130014' AND `castleId` = 9;
UPDATE `castle_door` SET `Name` = '門' WHERE `id` = '22130015' AND `castleId` = 9;

/***** sysstring-tw *****/ 
/***** char_templates.sql *****/
UPDATE `char_templates` SET ClassName = '戰士' where ClassId in (0);
UPDATE `char_templates` SET ClassName = '鬥士' where ClassId in (1);
UPDATE `char_templates` SET ClassName = '劍鬥士' where ClassId in (2);
UPDATE `char_templates` SET ClassName = '傭兵' where ClassId in (3);
UPDATE `char_templates` SET ClassName = '騎士' where ClassId in (4);
UPDATE `char_templates` SET ClassName = '聖騎士' where ClassId in (5);
UPDATE `char_templates` SET ClassName = '闇騎士' where ClassId in (6);
UPDATE `char_templates` SET ClassName = '盜賊' where ClassId in (7);
UPDATE `char_templates` SET ClassName = '寶藏獵人' where ClassId in (8);
UPDATE `char_templates` SET ClassName = '鷹眼' where ClassId in (9);
UPDATE `char_templates` SET ClassName = '法師' where ClassId in (10);
UPDATE `char_templates` SET ClassName = '巫師' where ClassId in (11);
UPDATE `char_templates` SET ClassName = '術士' where ClassId in (12);
UPDATE `char_templates` SET ClassName = '死靈法師' where ClassId in (13);
UPDATE `char_templates` SET ClassName = '法魔' where ClassId in (14);
UPDATE `char_templates` SET ClassName = '牧師' where ClassId in (15);
UPDATE `char_templates` SET ClassName = '主教' where ClassId in (16);
UPDATE `char_templates` SET ClassName = '先知' where ClassId in (17);
UPDATE `char_templates` SET ClassName = '精靈戰士' where ClassId in (18);
UPDATE `char_templates` SET ClassName = '精靈騎士' where ClassId in (19);
UPDATE `char_templates` SET ClassName = '聖殿騎士' where ClassId in (20);
UPDATE `char_templates` SET ClassName = '劍術詩人' where ClassId in (21);
UPDATE `char_templates` SET ClassName = '精靈巡守' where ClassId in (22);
UPDATE `char_templates` SET ClassName = '大地行者' where ClassId in (23);
UPDATE `char_templates` SET ClassName = '銀月遊俠' where ClassId in (24);
UPDATE `char_templates` SET ClassName = '精靈法師' where ClassId in (25);
UPDATE `char_templates` SET ClassName = '精靈巫師' where ClassId in (26);
UPDATE `char_templates` SET ClassName = '咒術詩人' where ClassId in (27);
UPDATE `char_templates` SET ClassName = '元素使' where ClassId in (28);
UPDATE `char_templates` SET ClassName = '神使' where ClassId in (29);
UPDATE `char_templates` SET ClassName = '長老' where ClassId in (30);
UPDATE `char_templates` SET ClassName = '黑暗戰士' where ClassId in (31);
UPDATE `char_templates` SET ClassName = '沼澤騎士' where ClassId in (32);
UPDATE `char_templates` SET ClassName = '席琳騎士' where ClassId in (33);
UPDATE `char_templates` SET ClassName = '劍刃舞者' where ClassId in (34);
UPDATE `char_templates` SET ClassName = '暗殺者' where ClassId in (35);
UPDATE `char_templates` SET ClassName = '深淵行者' where ClassId in (36);
UPDATE `char_templates` SET ClassName = '闇影遊俠' where ClassId in (37);
UPDATE `char_templates` SET ClassName = '黑暗法師' where ClassId in (38);
UPDATE `char_templates` SET ClassName = '黑暗巫師' where ClassId in (39);
UPDATE `char_templates` SET ClassName = '狂咒術士' where ClassId in (40);
UPDATE `char_templates` SET ClassName = '闇影召喚士' where ClassId in (41);
UPDATE `char_templates` SET ClassName = '席琳神使' where ClassId in (42);
UPDATE `char_templates` SET ClassName = '席琳長老' where ClassId in (43);
UPDATE `char_templates` SET ClassName = '半獸人戰士' where ClassId in (44);
UPDATE `char_templates` SET ClassName = '半獸人突擊者' where ClassId in (45);
UPDATE `char_templates` SET ClassName = '破壞者' where ClassId in (46);
UPDATE `char_templates` SET ClassName = '半獸人武者' where ClassId in (47);
UPDATE `char_templates` SET ClassName = '暴君' where ClassId in (48);
UPDATE `char_templates` SET ClassName = '半獸人法師' where ClassId in (49);
UPDATE `char_templates` SET ClassName = '半獸人巫醫' where ClassId in (50);
UPDATE `char_templates` SET ClassName = '霸主' where ClassId in (51);
UPDATE `char_templates` SET ClassName = '戰狂' where ClassId in (52);
UPDATE `char_templates` SET ClassName = '矮人戰士' where ClassId in (53);
UPDATE `char_templates` SET ClassName = '收集者' where ClassId in (54);
UPDATE `char_templates` SET ClassName = '賞金獵人' where ClassId in (55);
UPDATE `char_templates` SET ClassName = '工匠' where ClassId in (56);
UPDATE `char_templates` SET ClassName = '戰爭工匠' where ClassId in (57);
UPDATE `char_templates` SET ClassName = '決鬥者' where ClassId in (88);
UPDATE `char_templates` SET ClassName = '猛將' where ClassId in (89);
UPDATE `char_templates` SET ClassName = '聖凰騎士' where ClassId in (90);
UPDATE `char_templates` SET ClassName = '煉獄騎士' where ClassId in (91);
UPDATE `char_templates` SET ClassName = '人馬' where ClassId in (92);
UPDATE `char_templates` SET ClassName = '冒險英豪' where ClassId in (93);
UPDATE `char_templates` SET ClassName = '大魔導士' where ClassId in (94);
UPDATE `char_templates` SET ClassName = '魂狩術士' where ClassId in (95);
UPDATE `char_templates` SET ClassName = '祕儀召主' where ClassId in (96);
UPDATE `char_templates` SET ClassName = '樞機主教' where ClassId in (97);
UPDATE `char_templates` SET ClassName = '昭聖者' where ClassId in (98);
UPDATE `char_templates` SET ClassName = '伊娃神殿騎士' where ClassId in (99);
UPDATE `char_templates` SET ClassName = '伊娃吟遊詩人' where ClassId in (100);
UPDATE `char_templates` SET ClassName = '疾風浪人' where ClassId in (101);
UPDATE `char_templates` SET ClassName = '月光箭靈' where ClassId in (102);
UPDATE `char_templates` SET ClassName = '伊娃祕術詩人' where ClassId in (103);
UPDATE `char_templates` SET ClassName = '元素支配者' where ClassId in (104);
UPDATE `char_templates` SET ClassName = '伊娃聖者' where ClassId in (105);
UPDATE `char_templates` SET ClassName = '席琳冥殿騎士' where ClassId in (106);
UPDATE `char_templates` SET ClassName = '幽冥舞者' where ClassId in (107);
UPDATE `char_templates` SET ClassName = '魅影獵者' where ClassId in (108);
UPDATE `char_templates` SET ClassName = '幽冥箭靈' where ClassId in (109);
UPDATE `char_templates` SET ClassName = '暴風狂嘯者' where ClassId in (110);
UPDATE `char_templates` SET ClassName = '闇影支配者' where ClassId in (111);
UPDATE `char_templates` SET ClassName = '席琳聖者' where ClassId in (112);
UPDATE `char_templates` SET ClassName = '泰坦' where ClassId in (113);
UPDATE `char_templates` SET ClassName = '卡巴塔里宗師' where ClassId in (114);
UPDATE `char_templates` SET ClassName = '君主' where ClassId in (115);
UPDATE `char_templates` SET ClassName = '末日戰狂' where ClassId in (116);
UPDATE `char_templates` SET ClassName = '財富獵人' where ClassId in (117);
UPDATE `char_templates` SET ClassName = '巨匠' where ClassId in (118);
UPDATE `char_templates` SET ClassName = '闇天使士兵' where ClassId in (123);
UPDATE `char_templates` SET ClassName = '闇天使士兵' where ClassId in (124);
UPDATE `char_templates` SET ClassName = '裝甲突擊兵' where ClassId in (125);
UPDATE `char_templates` SET ClassName = '狙擊衛士' where ClassId in (126);
UPDATE `char_templates` SET ClassName = '狂戰士' where ClassId in (127);
UPDATE `char_templates` SET ClassName = '碎魂者' where ClassId in (128);
UPDATE `char_templates` SET ClassName = '碎魂者' where ClassId in (129);
UPDATE `char_templates` SET ClassName = '弩弓遊俠' where ClassId in (130);
UPDATE `char_templates` SET ClassName = '末日使者' where ClassId in (131);
UPDATE `char_templates` SET ClassName = '追魂使' where ClassId in (132);
UPDATE `char_templates` SET ClassName = '追魂使' where ClassId in (133);
UPDATE `char_templates` SET ClassName = '魔彈射手' where ClassId in (134);
UPDATE `char_templates` SET ClassName = '戰鬥巡官' where ClassId in (135);
UPDATE `char_templates` SET ClassName = '軍武判官' where ClassId in (136);

/***** castlename-tw *****/ 
/***** clanhall.sql *****/
UPDATE `clanhall` SET `name` = '反抗軍要塞', `location` = '狄恩', `desc` = '有豺狼游擊隊的根據地' WHERE `id` = '21';
UPDATE `clanhall` SET `name` = '古魯丁城鎮月長石廳', `location` = '古魯丁城鎮', `desc` = '在古魯丁城鎮的根據地' WHERE `id` = '22';
UPDATE `clanhall` SET `name` = '古魯丁城鎮瑪瑙廳', `location` = '古魯丁城鎮', `desc` = '在古魯丁城鎮的根據地' WHERE `id` = '23';
UPDATE `clanhall` SET `name` = '古魯丁城鎮黃玉廳', `location` = '古魯丁城鎮', `desc` = '在古魯丁城鎮的根據地' WHERE `id` = '24';
UPDATE `clanhall` SET `name` = '古魯丁城鎮紅寶石廳', `location` = '古魯丁城鎮', `desc` = '在古魯丁城鎮的根據地' WHERE `id` = '25';
UPDATE `clanhall` SET `name` = '古魯丁村莊水晶廳', `location` = '古魯丁村莊', `desc` = '在古魯丁村莊的根據地' WHERE `id` = '26';
UPDATE `clanhall` SET `name` = '古魯丁村莊瑪瑙廳', `location` = '古魯丁村莊', `desc` = '在古魯丁村莊的根據地' WHERE `id` = '27';
UPDATE `clanhall` SET `name` = '古魯丁村莊藍寶石廳', `location` = '古魯丁村莊', `desc` = '在古魯丁村莊的根據地' WHERE `id` = '28';
UPDATE `clanhall` SET `name` = '古魯丁村莊月長石廳', `location` = '古魯丁村莊', `desc` = '在古魯丁村莊的根據地' WHERE `id` = '29';
UPDATE `clanhall` SET `name` = '古魯丁村莊綠寶石廳', `location` = '古魯丁村莊', `desc` = '在古魯丁村莊的根據地' WHERE `id` = '30';
UPDATE `clanhall` SET `name` = '狄恩黑之公館', `location` = '狄恩', `desc` = '在狄恩城鎮的根據地' WHERE `id` = '31';
UPDATE `clanhall` SET `name` = '狄恩紅之公館', `location` = '狄恩', `desc` = '在狄恩城鎮的根據地' WHERE `id` = '32';
UPDATE `clanhall` SET `name` = '狄恩綠之公館', `location` = '狄恩', `desc` = '在狄恩城鎮的根據地' WHERE `id` = '33';
UPDATE `clanhall` SET `name` = '毀壞的城堡', `location` = '亞丁', `desc` = '' WHERE `id` = '34';
UPDATE `clanhall` SET `name` = '山賊城寨', `location` = '歐瑞', `desc` = '' WHERE `id` = '35';
UPDATE `clanhall` SET `name` = '亞丁黃金接待室', `location` = '亞丁', `desc` = '在亞丁城鎮的高級根據地' WHERE `id` = '36';
UPDATE `clanhall` SET `name` = '亞丁白銀接待室', `location` = '亞丁', `desc` = '在亞丁城鎮的高級根據地' WHERE `id` = '37';
UPDATE `clanhall` SET `name` = '亞丁米索莉接待室', `location` = '亞丁', `desc` = '在亞丁城鎮的高級根據地' WHERE `id` = '38';
UPDATE `clanhall` SET `name` = '亞丁銀色小屋', `location` = '亞丁', `desc` = '在亞丁城鎮的高級根據地' WHERE `id` = '39';
UPDATE `clanhall` SET `name` = '亞丁金色小屋', `location` = '亞丁', `desc` = '在亞丁城鎮的高級根據地' WHERE `id` = '40';
UPDATE `clanhall` SET `name` = '亞丁青銅接待室', `location` = '亞丁', `desc` = '在亞丁城鎮的高級根據地' WHERE `id` = '41';
UPDATE `clanhall` SET `name` = '奇岩黃金接待室', `location` = '奇岩', `desc` = '在奇岩城鎮的高級根據地' WHERE `id` = '42';
UPDATE `clanhall` SET `name` = '奇岩白銀接待室', `location` = '奇岩', `desc` = '在奇岩城鎮的高級根據地' WHERE `id` = '43';
UPDATE `clanhall` SET `name` = '奇岩米索莉接待室', `location` = '奇岩', `desc` = '在奇岩城鎮的高級根據地' WHERE `id` = '44';
UPDATE `clanhall` SET `name` = '奇岩青銅接待室', `location` = '奇岩', `desc` = '在奇岩城鎮的高級根據地' WHERE `id` = '45';
UPDATE `clanhall` SET `name` = '奇岩銀色小屋', `location` = '奇岩', `desc` = '在奇岩城鎮的高級根據地' WHERE `id` = '46';
UPDATE `clanhall` SET `name` = '高達特月長石廳', `location` = '高達特', `desc` = '在高達特城鎮的高級根據地' WHERE `id` = '47';
UPDATE `clanhall` SET `name` = '高達特瑪瑙廳', `location` = '高達特', `desc` = '在高達特城鎮的高級根據地' WHERE `id` = '48';
UPDATE `clanhall` SET `name` = '高達特綠寶石廳', `location` = '高達特', `desc` = '在高達特城鎮的高級根據地' WHERE `id` = '49';
UPDATE `clanhall` SET `name` = '高達特藍寶石廳', `location` = '高達特', `desc` = '在高達特城鎮的高級根據地' WHERE `id` = '50';
UPDATE `clanhall` SET `name` = '魯因蒙特接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '51';
UPDATE `clanhall` SET `name` = '魯因修特倫接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '52';
UPDATE `clanhall` SET `name` = '魯因維納斯接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '53';
UPDATE `clanhall` SET `name` = '魯因瑪爾斯接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '54';
UPDATE `clanhall` SET `name` = '魯因雅蒂斯接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '55';
UPDATE `clanhall` SET `name` = '魯因普魯托接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '56';
UPDATE `clanhall` SET `name` = '魯因特拉潘接待室', `location` = '魯因', `desc` = '在魯因城鎮的高級根據地' WHERE `id` = '57';
UPDATE `clanhall` SET `name` = '修加特鋼鐵之廳', `location` = '修加特', `desc` = '在修加特城鎮的高級根據地' WHERE `id` = '58';
UPDATE `clanhall` SET `name` = '修加特冷鑄之廳', `location` = '修加特', `desc` = '在修加特城鎮的高級根據地' WHERE `id` = '59';
UPDATE `clanhall` SET `name` = '修加特熱煉之廳', `location` = '修加特', `desc` = '在修加特城鎮的高級根據地' WHERE `id` = '60';
UPDATE `clanhall` SET `name` = '修加特鈦金之聽', `location` = '修加特', `desc` = '在修加特城鎮的高級根據地' WHERE `id` = '61';
UPDATE `clanhall` SET `name` = '虹彩之泉', `location` = '高達特', `desc` = '' WHERE `id` = '62';
UPDATE `clanhall` SET `name` = '野獸農莊', `location` = '魯因', `desc` = '' WHERE `id` = '63';
UPDATE `clanhall` SET `name` = '亡者的要塞', `location` = '魯因', `desc` = '' WHERE `id` = '64';

/***** npcname-tw *****/ 
/***** fish.sql *****/
UPDATE `fish` SET `name` = '敏捷的綠色小魚' WHERE `id` = '6411';
UPDATE `fish` SET `name` = '暴躁的綠色小魚' WHERE `id` = '6412';
UPDATE `fish` SET `name` = '寬扁的綠色小魚' WHERE `id` = '6413';
UPDATE `fish` SET `name` = '敏捷的綠色魚' WHERE `id` = '6414';
UPDATE `fish` SET `name` = '暴躁的綠色魚' WHERE `id` = '6415';
UPDATE `fish` SET `name` = '寬扁的綠色魚' WHERE `id` = '6416';
UPDATE `fish` SET `name` = '敏捷的綠色大魚' WHERE `id` = '6417';
UPDATE `fish` SET `name` = '暴躁的綠色大魚' WHERE `id` = '6418';
UPDATE `fish` SET `name` = '寬扁的綠色大魚' WHERE `id` = '6419';
UPDATE `fish` SET `name` = '敏捷的翡翠小魚' WHERE `id` = '6420';
UPDATE `fish` SET `name` = '暴躁的翡翠小魚' WHERE `id` = '6421';
UPDATE `fish` SET `name` = '寬扁的翡翠小魚' WHERE `id` = '6422';
UPDATE `fish` SET `name` = '敏捷的翡翠魚' WHERE `id` = '6423';
UPDATE `fish` SET `name` = '暴躁的翡翠魚' WHERE `id` = '6424';
UPDATE `fish` SET `name` = '寬扁的翡翠魚' WHERE `id` = '6425';
UPDATE `fish` SET `name` = '敏捷的翡翠大魚' WHERE `id` = '6426';
UPDATE `fish` SET `name` = '暴躁的翡翠大魚' WHERE `id` = '6427';
UPDATE `fish` SET `name` = '寬扁的翡翠大魚' WHERE `id` = '6428';
UPDATE `fish` SET `name` = '敏捷的藍色小魚' WHERE `id` = '6429';
UPDATE `fish` SET `name` = '暴躁的藍色小魚' WHERE `id` = '6430';
UPDATE `fish` SET `name` = '寬扁的藍色小魚' WHERE `id` = '6431';
UPDATE `fish` SET `name` = '敏捷的藍色魚' WHERE `id` = '6432';
UPDATE `fish` SET `name` = '暴躁的藍色魚' WHERE `id` = '6433';
UPDATE `fish` SET `name` = '寬扁的藍色魚' WHERE `id` = '6434';
UPDATE `fish` SET `name` = '敏捷的藍色大魚' WHERE `id` = '6435';
UPDATE `fish` SET `name` = '暴躁的藍色大魚' WHERE `id` = '6436';
UPDATE `fish` SET `name` = '寬扁的藍色大魚' WHERE `id` = '6437';
UPDATE `fish` SET `name` = '敏捷的黃色小魚' WHERE `id` = '6438';
UPDATE `fish` SET `name` = '暴躁的黃色小魚' WHERE `id` = '6439';
UPDATE `fish` SET `name` = '寬扁的黃色小魚' WHERE `id` = '6440';
UPDATE `fish` SET `name` = '敏捷的黃色魚' WHERE `id` = '6441';
UPDATE `fish` SET `name` = '暴躁的黃色魚' WHERE `id` = '6442';
UPDATE `fish` SET `name` = '寬扁的黃色魚' WHERE `id` = '6443';
UPDATE `fish` SET `name` = '敏捷的黃色大魚' WHERE `id` = '6444';
UPDATE `fish` SET `name` = '暴躁的黃色大魚' WHERE `id` = '6445';
UPDATE `fish` SET `name` = '寬扁的黃色大魚' WHERE `id` = '6446';
UPDATE `fish` SET `name` = '敏捷的橙色小魚' WHERE `id` = '6447';
UPDATE `fish` SET `name` = '暴躁的橙色小魚' WHERE `id` = '6448';
UPDATE `fish` SET `name` = '寬扁的橙色小魚' WHERE `id` = '6449';
UPDATE `fish` SET `name` = '敏捷的橙色魚' WHERE `id` = '6450';
UPDATE `fish` SET `name` = '暴躁的橙色魚' WHERE `id` = '6451';
UPDATE `fish` SET `name` = '寬扁的橙色魚' WHERE `id` = '6452';
UPDATE `fish` SET `name` = '敏捷的橙色大魚' WHERE `id` = '6453';
UPDATE `fish` SET `name` = '暴躁的橙色大魚' WHERE `id` = '6454';
UPDATE `fish` SET `name` = '寬扁的橙色大魚' WHERE `id` = '6455';
UPDATE `fish` SET `name` = '敏捷的紫色小魚' WHERE `id` = '6456';
UPDATE `fish` SET `name` = '暴躁的紫色小魚' WHERE `id` = '6457';
UPDATE `fish` SET `name` = '寬扁的紫色小魚' WHERE `id` = '6458';
UPDATE `fish` SET `name` = '敏捷的紫色魚' WHERE `id` = '6459';
UPDATE `fish` SET `name` = '暴躁的紫色魚' WHERE `id` = '6460';
UPDATE `fish` SET `name` = '寬扁的紫色魚' WHERE `id` = '6461';
UPDATE `fish` SET `name` = '敏捷的紫色大魚' WHERE `id` = '6462';
UPDATE `fish` SET `name` = '暴躁的紫色大魚' WHERE `id` = '6463';
UPDATE `fish` SET `name` = '寬扁的紫色大魚' WHERE `id` = '6464';
UPDATE `fish` SET `name` = '敏捷的紅色小魚' WHERE `id` = '6465';
UPDATE `fish` SET `name` = '暴躁的紅色小魚' WHERE `id` = '6466';
UPDATE `fish` SET `name` = '寬扁的紅色小魚' WHERE `id` = '6467';
UPDATE `fish` SET `name` = '敏捷的紅色魚' WHERE `id` = '6468';
UPDATE `fish` SET `name` = '暴躁的紅色魚' WHERE `id` = '6469';
UPDATE `fish` SET `name` = '寬扁的紅色魚' WHERE `id` = '6470';
UPDATE `fish` SET `name` = '敏捷的紅色大魚' WHERE `id` = '6471';
UPDATE `fish` SET `name` = '暴躁的紅色大魚' WHERE `id` = '6472';
UPDATE `fish` SET `name` = '寬扁的紅色大魚' WHERE `id` = '6473';
UPDATE `fish` SET `name` = '敏捷的白色小魚' WHERE `id` = '6474';
UPDATE `fish` SET `name` = '暴躁的白色小魚' WHERE `id` = '6475';
UPDATE `fish` SET `name` = '寬扁的白色小魚' WHERE `id` = '6476';
UPDATE `fish` SET `name` = '敏捷的白色魚' WHERE `id` = '6477';
UPDATE `fish` SET `name` = '暴躁的白色魚' WHERE `id` = '6478';
UPDATE `fish` SET `name` = '寬扁的白色魚' WHERE `id` = '6479';
UPDATE `fish` SET `name` = '敏捷的白色大魚' WHERE `id` = '6480';
UPDATE `fish` SET `name` = '暴躁的白色大魚' WHERE `id` = '6481';
UPDATE `fish` SET `name` = '寬扁的白色大魚' WHERE `id` = '6482';
UPDATE `fish` SET `name` = '敏捷的黑色小魚' WHERE `id` = '6483';
UPDATE `fish` SET `name` = '暴躁的黑色小魚' WHERE `id` = '6484';
UPDATE `fish` SET `name` = '寬扁的黑色小魚' WHERE `id` = '6485';
UPDATE `fish` SET `name` = '敏捷的黑色魚' WHERE `id` = '6486';
UPDATE `fish` SET `name` = '暴躁的黑色魚' WHERE `id` = '6487';
UPDATE `fish` SET `name` = '寬扁的黑色魚' WHERE `id` = '6488';
UPDATE `fish` SET `name` = '敏捷的黑色大魚' WHERE `id` = '6489';
UPDATE `fish` SET `name` = '暴躁的黑色大魚' WHERE `id` = '6490';
UPDATE `fish` SET `name` = '寬扁的黑色大魚' WHERE `id` = '6491';
UPDATE `fish` SET `name` = '綠色小寶箱' WHERE `id` = '6492';
UPDATE `fish` SET `name` = '綠色寶箱' WHERE `id` = '6493';
UPDATE `fish` SET `name` = '綠色大寶箱' WHERE `id` = '6494';
UPDATE `fish` SET `name` = '翡翠小寶箱' WHERE `id` = '6495';
UPDATE `fish` SET `name` = '翡翠寶箱' WHERE `id` = '6496';
UPDATE `fish` SET `name` = '翡翠大寶箱' WHERE `id` = '6497';
UPDATE `fish` SET `name` = '藍色小寶箱' WHERE `id` = '6498';
UPDATE `fish` SET `name` = '藍色寶箱' WHERE `id` = '6499';
UPDATE `fish` SET `name` = '藍色大寶箱' WHERE `id` = '6500';
UPDATE `fish` SET `name` = '黃色小寶箱' WHERE `id` = '6501';
UPDATE `fish` SET `name` = '黃色寶箱' WHERE `id` = '6502';
UPDATE `fish` SET `name` = '黃色大寶箱' WHERE `id` = '6503';
UPDATE `fish` SET `name` = '橙色小寶箱' WHERE `id` = '6504';
UPDATE `fish` SET `name` = '橙色寶箱' WHERE `id` = '6505';
UPDATE `fish` SET `name` = '橙色大寶箱' WHERE `id` = '6506';
UPDATE `fish` SET `name` = '紫色小寶箱' WHERE `id` = '6507';
UPDATE `fish` SET `name` = '紫色寶箱' WHERE `id` = '6508';
UPDATE `fish` SET `name` = '紫色大寶箱' WHERE `id` = '6509';
UPDATE `fish` SET `name` = '紅色小寶箱' WHERE `id` = '6510';
UPDATE `fish` SET `name` = '紅色寶箱' WHERE `id` = '6511';
UPDATE `fish` SET `name` = '紅色大寶箱' WHERE `id` = '6512';
UPDATE `fish` SET `name` = '白色小寶箱' WHERE `id` = '6513';
UPDATE `fish` SET `name` = '白色寶箱' WHERE `id` = '6514';
UPDATE `fish` SET `name` = '白色大寶箱' WHERE `id` = '6515';
UPDATE `fish` SET `name` = '黑色小寶箱' WHERE `id` = '6516';
UPDATE `fish` SET `name` = '黑色寶箱' WHERE `id` = '6517';
UPDATE `fish` SET `name` = '黑色大寶箱' WHERE `id` = '6518';
UPDATE `fish` SET `name` = '初學者用-敏捷的綠色小魚' WHERE `id` = '7726';
UPDATE `fish` SET `name` = '初學者用-暴躁的綠色小魚' WHERE `id` = '7727';
UPDATE `fish` SET `name` = '初學者用-寬扁的綠色小魚' WHERE `id` = '7728';
UPDATE `fish` SET `name` = '初學者用-敏捷的綠色魚' WHERE `id` = '7729';
UPDATE `fish` SET `name` = '初學者用-暴躁的綠色魚' WHERE `id` = '7730';
UPDATE `fish` SET `name` = '初學者用-寬扁的綠色魚' WHERE `id` = '7731';
UPDATE `fish` SET `name` = '初學者用-敏捷的綠色大魚' WHERE `id` = '7732';
UPDATE `fish` SET `name` = '初學者用-暴躁的綠色大魚' WHERE `id` = '7733';
UPDATE `fish` SET `name` = '初學者用-寬扁的綠色大魚' WHERE `id` = '7734';
UPDATE `fish` SET `name` = '初學者用-敏捷的翡翠小魚' WHERE `id` = '7735';
UPDATE `fish` SET `name` = '初學者用-暴躁的翡翠小魚' WHERE `id` = '7736';
UPDATE `fish` SET `name` = '初學者用-寬扁的翡翠小魚' WHERE `id` = '7737';
UPDATE `fish` SET `name` = '初學者用-敏捷的翡翠魚' WHERE `id` = '7738';
UPDATE `fish` SET `name` = '初學者用-暴躁的翡翠魚' WHERE `id` = '7739';
UPDATE `fish` SET `name` = '初學者用-寬扁的翡翠魚' WHERE `id` = '7740';
UPDATE `fish` SET `name` = '初學者用-敏捷的翡翠大魚' WHERE `id` = '7741';
UPDATE `fish` SET `name` = '初學者用-暴躁的翡翠大魚' WHERE `id` = '7742';
UPDATE `fish` SET `name` = '初學者用-寬扁的翡翠大魚' WHERE `id` = '7743';
UPDATE `fish` SET `name` = '初學者用-敏捷的藍色小魚' WHERE `id` = '7744';
UPDATE `fish` SET `name` = '初學者用-暴躁的藍色小魚' WHERE `id` = '7745';
UPDATE `fish` SET `name` = '初學者用-寬扁的藍色小魚' WHERE `id` = '7746';
UPDATE `fish` SET `name` = '初學者用-敏捷的藍色魚' WHERE `id` = '7747';
UPDATE `fish` SET `name` = '初學者用-暴躁的藍色魚' WHERE `id` = '7748';
UPDATE `fish` SET `name` = '初學者用-寬扁的藍色魚' WHERE `id` = '7749';
UPDATE `fish` SET `name` = '初學者用-敏捷的藍色大魚' WHERE `id` = '7750';
UPDATE `fish` SET `name` = '初學者用-暴躁的藍色大魚' WHERE `id` = '7751';
UPDATE `fish` SET `name` = '初學者用-寬扁的藍色大魚' WHERE `id` = '7752';
UPDATE `fish` SET `name` = '初學者用-敏捷的黃色小魚' WHERE `id` = '7753';
UPDATE `fish` SET `name` = '初學者用-暴躁的黃色小魚' WHERE `id` = '7754';
UPDATE `fish` SET `name` = '初學者用-寬扁的黃色小魚' WHERE `id` = '7755';
UPDATE `fish` SET `name` = '初學者用-敏捷的黃色魚' WHERE `id` = '7756';
UPDATE `fish` SET `name` = '初學者用-暴躁的黃色魚' WHERE `id` = '7757';
UPDATE `fish` SET `name` = '初學者用-寬扁的黃色魚' WHERE `id` = '7758';
UPDATE `fish` SET `name` = '初學者用-敏捷的黃色大魚' WHERE `id` = '7759';
UPDATE `fish` SET `name` = '初學者用-暴躁的黃色大魚' WHERE `id` = '7760';
UPDATE `fish` SET `name` = '初學者用-寬扁的黃色大魚' WHERE `id` = '7761';
UPDATE `fish` SET `name` = '初學者用-敏捷的橙色小魚' WHERE `id` = '7762';
UPDATE `fish` SET `name` = '初學者用-暴躁的橙色小魚' WHERE `id` = '7763';
UPDATE `fish` SET `name` = '初學者用-寬扁的橙色小魚' WHERE `id` = '7764';
UPDATE `fish` SET `name` = '初學者用-敏捷的橙色魚' WHERE `id` = '7765';
UPDATE `fish` SET `name` = '初學者用-暴躁的橙色魚' WHERE `id` = '7766';
UPDATE `fish` SET `name` = '初學者用-寬扁的橙色魚' WHERE `id` = '7767';
UPDATE `fish` SET `name` = '初學者用-敏捷的橙色大魚' WHERE `id` = '7768';
UPDATE `fish` SET `name` = '初學者用-暴躁的橙色大魚' WHERE `id` = '7769';
UPDATE `fish` SET `name` = '初學者用-寬扁的橙色大魚' WHERE `id` = '7770';
UPDATE `fish` SET `name` = '初學者用-敏捷的紫色小魚' WHERE `id` = '7771';
UPDATE `fish` SET `name` = '初學者用-暴躁的紫色小魚' WHERE `id` = '7772';
UPDATE `fish` SET `name` = '初學者用-寬扁的紫色小魚' WHERE `id` = '7773';
UPDATE `fish` SET `name` = '初學者用-敏捷的紫色魚' WHERE `id` = '7774';
UPDATE `fish` SET `name` = '初學者用-暴躁的紫色魚' WHERE `id` = '7775';
UPDATE `fish` SET `name` = '初學者用-寬扁的紫色魚' WHERE `id` = '7776';
UPDATE `fish` SET `name` = '初學者用-敏捷的紫色大魚' WHERE `id` = '7777';
UPDATE `fish` SET `name` = '初學者用-暴躁的紫色大魚' WHERE `id` = '7778';
UPDATE `fish` SET `name` = '初學者用-寬扁的紫色大魚' WHERE `id` = '7779';
UPDATE `fish` SET `name` = '初學者用-敏捷的紅色小魚' WHERE `id` = '7780';
UPDATE `fish` SET `name` = '初學者用-暴躁的紅色小魚' WHERE `id` = '7781';
UPDATE `fish` SET `name` = '初學者用-寬扁的紅色小魚' WHERE `id` = '7782';
UPDATE `fish` SET `name` = '初學者用-敏捷的紅色魚' WHERE `id` = '7783';
UPDATE `fish` SET `name` = '初學者用-暴躁的紅色魚' WHERE `id` = '7784';
UPDATE `fish` SET `name` = '初學者用-寬扁的紅色魚' WHERE `id` = '7785';
UPDATE `fish` SET `name` = '初學者用-敏捷的紅色大魚' WHERE `id` = '7786';
UPDATE `fish` SET `name` = '初學者用-暴躁的紅色大魚' WHERE `id` = '7787';
UPDATE `fish` SET `name` = '初學者用-寬扁的紅色大魚' WHERE `id` = '7788';
UPDATE `fish` SET `name` = '初學者用-敏捷的白色小魚' WHERE `id` = '7789';
UPDATE `fish` SET `name` = '初學者用-暴躁的白色小魚' WHERE `id` = '7790';
UPDATE `fish` SET `name` = '初學者用-寬扁的白色小魚' WHERE `id` = '7791';
UPDATE `fish` SET `name` = '初學者用-敏捷的白色魚' WHERE `id` = '7792';
UPDATE `fish` SET `name` = '初學者用-暴躁的白色魚' WHERE `id` = '7793';
UPDATE `fish` SET `name` = '初學者用-寬扁的白色魚' WHERE `id` = '7794';
UPDATE `fish` SET `name` = '初學者用-敏捷的白色大魚' WHERE `id` = '7795';
UPDATE `fish` SET `name` = '初學者用-暴躁的白色大魚' WHERE `id` = '7796';
UPDATE `fish` SET `name` = '初學者用-寬扁的白色大魚' WHERE `id` = '7797';
UPDATE `fish` SET `name` = '初學者用-敏捷的黑色小魚' WHERE `id` = '7798';
UPDATE `fish` SET `name` = '初學者用-暴躁的黑色小魚' WHERE `id` = '7799';
UPDATE `fish` SET `name` = '初學者用-寬扁的黑色小魚' WHERE `id` = '7800';
UPDATE `fish` SET `name` = '初學者用-敏捷的黑色魚' WHERE `id` = '7801';
UPDATE `fish` SET `name` = '初學者用-暴躁的黑色魚' WHERE `id` = '7802';
UPDATE `fish` SET `name` = '初學者用-寬扁的黑色魚' WHERE `id` = '7803';
UPDATE `fish` SET `name` = '初學者用-敏捷的黑色大魚' WHERE `id` = '7804';
UPDATE `fish` SET `name` = '初學者用-暴躁的黑色大魚' WHERE `id` = '7805';
UPDATE `fish` SET `name` = '初學者用-寬扁的黑色大魚' WHERE `id` = '7806';

/***** skillname-tw *****/ 
/***** fishing_skill_trees.sql *****/
UPDATE `fishing_skill_trees` SET `name` = '釣魚' WHERE `skill_id` = '1312';
UPDATE `fishing_skill_trees` SET `name` = '拉線' WHERE `skill_id` = '1313';
UPDATE `fishing_skill_trees` SET `name` = '放線' WHERE `skill_id` = '1314';
UPDATE `fishing_skill_trees` SET `name` = '精通釣魚' WHERE `skill_id` = '1315';
UPDATE `fishing_skill_trees` SET `name` = '擴充矮人工藝' WHERE `skill_id` = '1368';
UPDATE `fishing_skill_trees` SET `name` = '擴充一般工藝' WHERE `skill_id` = '1369';
UPDATE `fishing_skill_trees` SET `name` = '擴充個人商店' WHERE `skill_id` = '1370';
UPDATE `fishing_skill_trees` SET `name` = '擴充倉庫' WHERE `skill_id` = '1371';
UPDATE `fishing_skill_trees` SET `name` = '擴充包袱' WHERE `skill_id` = '1372';

/***** castlename-tw *****/ 
/***** fort.sql *****/
UPDATE `fort` SET `name` = '野營要塞' WHERE `id` = '101';
UPDATE `fort` SET `name` = '古魯丁南部要塞' WHERE `id` = '102';
UPDATE `fort` SET `name` = '蜂窩要塞' WHERE `id` = '103';
UPDATE `fort` SET `name` = '峽谷要塞' WHERE `id` = '104';
UPDATE `fort` SET `name` = '象牙塔要塞' WHERE `id` = '105';
UPDATE `fort` SET `name` = '湖泊要塞' WHERE `id` = '106';
UPDATE `fort` SET `name` = '盆地要塞' WHERE `id` = '107';
UPDATE `fort` SET `name` = '白沙灘要塞' WHERE `id` = '108';
UPDATE `fort` SET `name` = '前哨基地要塞' WHERE `id` = '109';
UPDATE `fort` SET `name` = '沼澤要塞' WHERE `id` = '110';
UPDATE `fort` SET `name` = '遺蹟要塞' WHERE `id` = '111';
UPDATE `fort` SET `name` = '芙羅蘭邊境要塞' WHERE `id` = '112';
UPDATE `fort` SET `name` = '薄霧山脈邊境要塞' WHERE `id` = '113';
UPDATE `fort` SET `name` = '塔諾邊境要塞' WHERE `id` = '114';
UPDATE `fort` SET `name` = '巨龍士伯吟邊境要塞' WHERE `id` = '115';
UPDATE `fort` SET `name` = '地龍的邊境要塞' WHERE `id` = '116';
UPDATE `fort` SET `name` = '西部國境邊境要塞' WHERE `id` = '117';
UPDATE `fort` SET `name` = '獵人的邊境要塞' WHERE `id` = '118';
UPDATE `fort` SET `name` = '平原邊境要塞' WHERE `id` = '119';
UPDATE `fort` SET `name` = '死靈的邊境要塞' WHERE `id` = '120';
UPDATE `fort` SET `name` = '聖者邊境要塞' WHERE `id` = '121';

/***** staticobject-tw *****/ 
/***** fort_staticobjects.sql *****/
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18200012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '18220008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '19240012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20200008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220017';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220018';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220019';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220020';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220021';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220022';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220023';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220024';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220025';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220026';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220027';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20220028';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '20230010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '21220008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22150008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22160012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22180008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22200012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '22230008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23130008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23160008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23170012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23200012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23210012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '23240008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24150012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24190005';
UPDATE `fort_staticobjects` SET `name` = '指揮幕舍之門' WHERE `id` = '24190006';
UPDATE `fort_staticobjects` SET `name` = '指揮幕舍之門' WHERE `id` = '24190007';
UPDATE `fort_staticobjects` SET `name` = '指揮幕舍之門' WHERE `id` = '24190008';
UPDATE `fort_staticobjects` SET `name` = '指揮幕舍之門' WHERE `id` = '24190009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24190010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24190011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '24190012';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190001';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190002';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190003';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190004';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190005';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190006';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190007';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190008';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190009';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190010';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190011';
UPDATE `fort_staticobjects` SET `name` = '要塞之門' WHERE `id` = '25190012';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '18220500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '19240500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '20230500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '23210500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '22180500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '24190500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '25190500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '23240500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '24150500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '22160500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '23130500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '20220500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '18200500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '21220500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '20200500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '22200500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '23170500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '23200500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '22230500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '23160500';
UPDATE `fort_staticobjects` SET `name` = '旗座' WHERE `id` = '22150500';

/***** skillname-tw *****/ 
/***** helper_buff_list.sql *****/
UPDATE `helper_buff_list` SET `name` = '冒險家用風之疾走' WHERE `skill_id` = '4322';
UPDATE `helper_buff_list` SET `name` = '冒險家用保護盾' WHERE `skill_id` = '4323';
UPDATE `helper_buff_list` SET `name` = '冒險家用神佑之體' WHERE `skill_id` = '4324';
UPDATE `helper_buff_list` SET `name` = '冒險家用吸血怒擊' WHERE `skill_id` = '4325';
UPDATE `helper_buff_list` SET `name` = '冒險家用強癒術' WHERE `skill_id` = '4326';
UPDATE `helper_buff_list` SET `name` = '冒險家用速度激發' WHERE `skill_id` = '4327';
UPDATE `helper_buff_list` SET `name` = '冒險家用神佑之魂' WHERE `skill_id` = '4328';
UPDATE `helper_buff_list` SET `name` = '冒險家用靈活思緒' WHERE `skill_id` = '4329';
UPDATE `helper_buff_list` SET `name` = '冒險家用精神專注' WHERE `skill_id` = '4330';
UPDATE `helper_buff_list` SET `name` = '冒險家用魔力催化' WHERE `skill_id` = '4331';
UPDATE `helper_buff_list` SET `name` = '冒險家用治癒晶體' WHERE `skill_id` = '4338';
UPDATE `helper_buff_list` SET `name` = '冒險家用 速度激發' WHERE `skill_id` = '5632';
UPDATE `helper_buff_list` SET `name` = '冒險家用 魔法屏障' WHERE `skill_id` = '5637';

/***** hennagrp-tw *****/ 
/***** henna.sql *****/
UPDATE `henna` SET `symbol_name` = '力量紋章' WHERE `dye_id` = '4445';
UPDATE `henna` SET `symbol_name` = '力量紋章' WHERE `dye_id` = '4446';
UPDATE `henna` SET `symbol_name` = '體質紋章' WHERE `dye_id` = '4447';
UPDATE `henna` SET `symbol_name` = '體質紋章' WHERE `dye_id` = '4448';
UPDATE `henna` SET `symbol_name` = '敏捷紋章' WHERE `dye_id` = '4449';
UPDATE `henna` SET `symbol_name` = '敏捷紋章' WHERE `dye_id` = '4450';
UPDATE `henna` SET `symbol_name` = '智力紋章' WHERE `dye_id` = '4451';
UPDATE `henna` SET `symbol_name` = '智力紋章' WHERE `dye_id` = '4452';
UPDATE `henna` SET `symbol_name` = '精神紋章' WHERE `dye_id` = '4453';
UPDATE `henna` SET `symbol_name` = '精神紋章' WHERE `dye_id` = '4454';
UPDATE `henna` SET `symbol_name` = '智慧紋章' WHERE `dye_id` = '4455';
UPDATE `henna` SET `symbol_name` = '智慧紋章' WHERE `dye_id` = '4456';
UPDATE `henna` SET `symbol_name` = '力量紋章' WHERE `dye_id` = '4457';
UPDATE `henna` SET `symbol_name` = '力量紋章' WHERE `dye_id` = '4458';
UPDATE `henna` SET `symbol_name` = '體質紋章' WHERE `dye_id` = '4459';
UPDATE `henna` SET `symbol_name` = '體質紋章' WHERE `dye_id` = '4460';
UPDATE `henna` SET `symbol_name` = '敏捷紋章' WHERE `dye_id` = '4461';
UPDATE `henna` SET `symbol_name` = '敏捷紋章' WHERE `dye_id` = '4462';
UPDATE `henna` SET `symbol_name` = '智力紋章' WHERE `dye_id` = '4463';
UPDATE `henna` SET `symbol_name` = '智力紋章' WHERE `dye_id` = '4464';
UPDATE `henna` SET `symbol_name` = '精神紋章' WHERE `dye_id` = '4465';
UPDATE `henna` SET `symbol_name` = '精神紋章' WHERE `dye_id` = '4466';
UPDATE `henna` SET `symbol_name` = '智慧紋章' WHERE `dye_id` = '4467';
UPDATE `henna` SET `symbol_name` = '智慧紋章' WHERE `dye_id` = '4468';
UPDATE `henna` SET `symbol_name` = '力量紋章' WHERE `dye_id` = '4469';
UPDATE `henna` SET `symbol_name` = '力量紋章' WHERE `dye_id` = '4470';
UPDATE `henna` SET `symbol_name` = '體質紋章' WHERE `dye_id` = '4471';
UPDATE `henna` SET `symbol_name` = '體質紋章' WHERE `dye_id` = '4472';
UPDATE `henna` SET `symbol_name` = '敏捷紋章' WHERE `dye_id` = '4473';
UPDATE `henna` SET `symbol_name` = '敏捷紋章' WHERE `dye_id` = '4474';
UPDATE `henna` SET `symbol_name` = '智力紋章' WHERE `dye_id` = '4475';
UPDATE `henna` SET `symbol_name` = '智力紋章' WHERE `dye_id` = '4476';
UPDATE `henna` SET `symbol_name` = '精神紋章' WHERE `dye_id` = '4477';
UPDATE `henna` SET `symbol_name` = '精神紋章' WHERE `dye_id` = '4478';
UPDATE `henna` SET `symbol_name` = '智慧紋章' WHERE `dye_id` = '4479';
UPDATE `henna` SET `symbol_name` = '智慧紋章' WHERE `dye_id` = '4480';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4481';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4482';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4483';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4484';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4485';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4486';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4487';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4488';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4489';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4490';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4491';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4492';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4493';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4494';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4495';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4496';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4497';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4498';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4499';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4500';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4501';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4502';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4503';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4504';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4505';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4506';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4507';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4508';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4509';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4510';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4511';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4512';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4513';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4514';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4515';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4516';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4517';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4518';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4519';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4520';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4521';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4522';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4523';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4524';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4525';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4526';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4527';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4528';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4529';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4530';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4531';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4532';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4533';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4534';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4535';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4536';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4537';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4538';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4539';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4540';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4541';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4542';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4543';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4544';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4545';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4546';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4547';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4548';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4549';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4550';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4551';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4552';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4553';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4554';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4555';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4556';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4557';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4558';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4559';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4560';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4561';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4562';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4563';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4564';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4565';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4566';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4567';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4568';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4569';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4570';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4571';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4572';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4573';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4574';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4575';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4576';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4577';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4578';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4579';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4580';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4581';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4582';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4583';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4584';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4585';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4586';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4587';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4588';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4589';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4590';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4591';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4592';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4593';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4594';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4595';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4596';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4597';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4598';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4599';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4600';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4601';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4602';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4603';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4604';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4605';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4606';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4607';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4608';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4609';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4610';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4611';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4612';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4613';
UPDATE `henna` SET `symbol_name` = '高級力量紋章' WHERE `dye_id` = '4614';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4615';
UPDATE `henna` SET `symbol_name` = '高級體質紋章' WHERE `dye_id` = '4616';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4617';
UPDATE `henna` SET `symbol_name` = '高級敏捷紋章' WHERE `dye_id` = '4618';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4619';
UPDATE `henna` SET `symbol_name` = '高級智力紋章' WHERE `dye_id` = '4620';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4621';
UPDATE `henna` SET `symbol_name` = '高級精神紋章' WHERE `dye_id` = '4622';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4623';
UPDATE `henna` SET `symbol_name` = '高級智慧紋章' WHERE `dye_id` = '4624';

/***** skillname-tw *****/ 
/***** pledge_skill_trees.sql *****/
UPDATE `pledge_skill_trees` SET `name` ='盟誓-血盟體魄' ,`Description` ='增加血盟成員的HP最大值。效果適用於名門階級以上。' WHERE `skill_id` ='370';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-血盟精神' ,`Description` ='增加血盟成員的CP最大值。效果適用於男爵階級以上。' WHERE `skill_id` ='371';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-血盟靈魂' ,`Description` ='增加血盟成員的MP最大值。效果適用於子爵階級以上。' WHERE `skill_id` ='372';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-奮戰不懈' ,`Description` ='提升血盟成員的HP恢復力。效果適用於名門階級以上。' WHERE `skill_id` ='373';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-士氣高昂' ,`Description` ='提升血盟成員的CP恢復力。效果適用於智者階級以上。' WHERE `skill_id` ='374';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-沉著冷靜' ,`Description` ='提升血盟成員的MP自然恢復力。效果適用於子爵階級以上。' WHERE `skill_id` ='375';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-威猛剛健' ,`Description` ='提升血盟成員的物理攻擊力。效果適用於騎士階級以上。' WHERE `skill_id` ='376';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-堅定不移' ,`Description` ='提升血盟成員的物理防禦力。效果適用於騎士階級以上。' WHERE `skill_id` ='377';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-英明睿智' ,`Description` ='提升血盟成員的魔法攻擊力。效果適用於子爵階級以上。' WHERE `skill_id` ='378';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-鋼鐵意志' ,`Description` ='提升血盟成員的魔法防禦力。效果適用於名門階級以上。' WHERE `skill_id` ='379';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-將士用命' ,`Description` ='提升血盟成員的命中能力。效果適用於男爵階級以上。' WHERE `skill_id` ='380';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-謀定後動' ,`Description` ='提升血盟成員的迴避能力。效果適用於男爵階級以上。' WHERE `skill_id` ='381';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-騎士精神' ,`Description` ='提高血盟成員的盾牌的防禦機率。效果適用於子爵階級以上。' WHERE `skill_id` ='382';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-騎士榮耀' ,`Description` ='提升血盟成員的盾牌防禦力。效果適用於男爵階級以上。' WHERE `skill_id` ='383';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-風雨無阻' ,`Description` ='提升血盟成員對水/風屬性的抗性。效果適用於子爵階級以上。' WHERE `skill_id` ='384';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-百鍊成鋼' ,`Description` ='提升血盟成員對火/大地屬性的抗性。效果適用於子爵階級以上。' WHERE `skill_id` ='385';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-威武不屈' ,`Description` ='提升血盟成員對衝擊屬性的抗性。效果適用於子爵階級以上。' WHERE `skill_id` ='386';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-勇往直前' ,`Description` ='提升血盟成員對束縛屬性的抗性。效果適用於子爵階級以上。' WHERE `skill_id` ='387';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-盡忠職守' ,`Description` ='提升血盟成員對睡眠屬性的抗性。效果適用於子爵階級以上。' WHERE `skill_id` ='388';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-兵貴神速' ,`Description` ='加快血盟成員的移動速度。效果適用於伯爵階級以上。' WHERE `skill_id` ='389';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-鞠躬盡瘁' ,`Description` ='血盟成員因PK或怪物攻擊導致死亡時，減少經驗值下降的比率並降低產生死亡後遺症的機率。效果適用於名門階級以上。' WHERE `skill_id` ='390';
UPDATE `pledge_skill_trees` SET `name` ='盟誓-帝權授命' ,`Description` ='賦予可組成聯合軍的權限。效果適用於智者階級以上。' WHERE `skill_id` ='391';

/***** skillname-tw *****/ 
/***** transform_skill_trees.sql *****/
UPDATE `transform_skill_trees` SET `name` = '變身 門徒聖杯' WHERE skill_id in(541,542,543);
UPDATE `transform_skill_trees` SET `name` = '變身 獨角獸' WHERE skill_id in(544,545,546);
UPDATE `transform_skill_trees` SET `name` = '變身 莉莉恩騎士' WHERE skill_id in(547,548,549);
UPDATE `transform_skill_trees` SET `name` = '變身 高崙守護者' WHERE skill_id in(550,551,552);
UPDATE `transform_skill_trees` SET `name` = '變身 煉獄龍獸' WHERE skill_id in(553,554,555);
UPDATE `transform_skill_trees` SET `name` = '變身 暴烈龍' WHERE skill_id in(556,557,558);
UPDATE `transform_skill_trees` SET `name` = '變身 瑪瑙獸' WHERE skill_id ='617';
UPDATE `transform_skill_trees` SET `name` = '變身 死亡之刃' WHERE skill_id ='618';
UPDATE `transform_skill_trees` SET `name` = '變身 札肯' WHERE `skill_id` = '663';
UPDATE `transform_skill_trees` SET `name` = '變身 亞納' WHERE `skill_id` = '664';
UPDATE `transform_skill_trees` SET `name` = '變身 貝諾姆' WHERE `skill_id` = '665';
UPDATE `transform_skill_trees` SET `name` = '變身 高登' WHERE `skill_id` = '666';
UPDATE `transform_skill_trees` SET `name` = '變身 勞庫' WHERE `skill_id` = '667';
UPDATE `transform_skill_trees` SET `name` = '變身 基亞齊' WHERE `skill_id` = '668';
UPDATE `transform_skill_trees` SET `name` = '變身 惡魔公爵' WHERE `skill_id` = '669';
UPDATE `transform_skill_trees` SET `name` = '變身 異教徒' WHERE `skill_id` = '670';
UPDATE `transform_skill_trees` SET `name` = '變身 貝里大師' WHERE `skill_id` = '671';
UPDATE `transform_skill_trees` SET `name` = '變身 劍齒虎' WHERE `skill_id` = '672';
UPDATE `transform_skill_trees` SET `name` = '變身 奧耶豺狼' WHERE `skill_id` = '673';
UPDATE `transform_skill_trees` SET `name` = '變身 人偶刀手' WHERE `skill_id` = '674';

/***** 闇天使版資料 *****/ 
/***** walker_routes.sql *****/
/***** 黑暗精靈村莊 *****/
/***** 31361 長老執行者 克里德 *****/
UPDATE `walker_routes` SET `chatText` = '幾天後將開始黑暗儀式，需要更注重警備工作！' WHERE `route_id` = '1' AND `move_point` = 5;
/***** 31360 長老代理人艾爾海娜 *****/
UPDATE `walker_routes` SET `chatText` = '您很辛苦。萊伊爾拉！' WHERE `route_id` = '2' AND `move_point` = 5;
UPDATE `walker_routes` SET `chatText` = '多勞您辛苦了！' WHERE `route_id` = '2' AND `move_point` = 11;

/***** 矮人村莊 *****/
/***** 31362 使者 泰特 *****/
UPDATE `walker_routes` SET `chatText` = '里德！ 摩普琳！ 艾兒黎！ 你們大家都好嗎？' WHERE `route_id` = '3' AND `move_point` = 1;
UPDATE `walker_routes` SET `chatText` = '好！那麼就開始轉一轉？' WHERE `route_id` = '3' AND `move_point` = 7;
UPDATE `walker_routes` SET `chatText` = '卡黎塔！ 米恩！ 很愉快的一天！' WHERE `route_id` = '3' AND `move_point` = 12;
/***** 31363 信使 洛金 *****/
UPDATE `walker_routes` SET `chatText` = '那個鼠輩！ 到底躲在哪兒？' WHERE `route_id` = '4' AND `move_point` = 1;
UPDATE `walker_routes` SET `chatText` = '今天你沒看到吐魯克嗎？' WHERE `route_id` = '4' AND `move_point` = 7;
UPDATE `walker_routes` SET `chatText` = '你沒看到吐魯克嗎？' WHERE `route_id` = '4' AND `move_point` = 10;

/***** 精靈村莊 *****/
/***** 31359 世界樹守護者 傑洛迪 *****/
UPDATE `walker_routes` SET `chatText` = '為了救活世界樹該怎麼做？' WHERE `route_id` = '5' AND `move_point` = 3;
UPDATE `walker_routes` SET `chatText` = '世界樹在逐漸凋零枯萎...' WHERE `route_id` = '5' AND `move_point` = 4;
UPDATE `walker_routes` SET `chatText` = '世界樹在逐漸凋零枯萎...' WHERE `route_id` = '5' AND `move_point` = 10;
UPDATE `walker_routes` SET `chatText` = '為了救活世界樹該怎麼做？' WHERE `route_id` = '5' AND `move_point` = 11;
/***** 31358 吟遊詩人 卡斯爾 *****/
UPDATE `walker_routes` SET `chatText` = '米帝爾，湖水的和平與你同在..' WHERE `route_id` = '6' AND `move_point` = 1;
UPDATE `walker_routes` SET `chatText` = '無論何時凝視世界樹都是如此美麗..' WHERE `route_id` = '6' AND `move_point` = 5;
UPDATE `walker_routes` SET `chatText` = '無論何時凝視世界樹都是如此美麗..' WHERE `route_id` = '6' AND `move_point` = 13;

/***** 說話之島村莊 *****/
/***** 31357 書記官 萊安德路 *****/
UPDATE `walker_routes` SET `chatText` = '他到底在哪裡呢？' WHERE `route_id` = '7' AND `move_point` = 1;
UPDATE `walker_routes` SET `chatText` = '你有看到溫達伍德嗎？' WHERE `route_id` = '7' AND `move_point` = 4;
UPDATE `walker_routes` SET `chatText` = '到底去哪裡呢？' WHERE `route_id` = '7' AND `move_point` = 6;
UPDATE `walker_routes` SET `chatText` = '到底去哪裡呢？' WHERE `route_id` = '7' AND `move_point` = 16;
UPDATE `walker_routes` SET `chatText` = '你有看到溫達伍德嗎？' WHERE `route_id` = '7' AND `move_point` = 18;
/***** 31356 使者 雷米 *****/
UPDATE `walker_routes` SET `chatText` = '運送給雷克特？好好，知道了~' WHERE `route_id` = '8' AND `move_point` = 1;
UPDATE `walker_routes` SET `chatText` = '哎呀！要稍微休息一下~' WHERE `route_id` = '8' AND `move_point` = 5;
UPDATE `walker_routes` SET `chatText` = '你好！雷克特！傑克森也好久不見！' WHERE `route_id` = '8' AND `move_point` = 9;
UPDATE `walker_routes` SET `chatText` = '啦啦啦啦~' WHERE `route_id` = '8' AND `move_point` = 14;
UPDATE `walker_routes` SET `chatText` = '啦啦啦啦~' WHERE `route_id` = '8' AND `move_point` = 15;
UPDATE `walker_routes` SET `chatText` = '啦啦啦啦~' WHERE `route_id` = '8' AND `move_point` = 16;

/***** Done by vdmyagami！ *****/