/************ Made in Taiwan ************/

/***** 貳幕繽炫風 11-11 *****/ 
/***** skillname-tw *****/ 
UPDATE `skill_trees` SET `name` = '三連斬' WHERE `skill_id` = '1';
UPDATE `skill_trees` SET `name` = '混亂術' WHERE `skill_id` = '2';
UPDATE `skill_trees` SET `name` = '強力攻擊' WHERE `skill_id` = '3';
UPDATE `skill_trees` SET `name` = '衝刺' WHERE `skill_id` = '4';
UPDATE `skill_trees` SET `name` = '波動連斬' WHERE `skill_id` = '5';
UPDATE `skill_trees` SET `name` = '波動衝擊' WHERE `skill_id` = '6';
UPDATE `skill_trees` SET `name` = '波動風暴' WHERE `skill_id` = '7';
UPDATE `skill_trees` SET `name` = '波動凝聚' WHERE `skill_id` = '8';
UPDATE `skill_trees` SET `name` = '波動爆破' WHERE `skill_id` = '9';
UPDATE `skill_trees` SET `name` = '召喚暴風晶體' WHERE `skill_id` = '10';
UPDATE `skill_trees` SET `name` = '誘騙術' WHERE `skill_id` = '11';
UPDATE `skill_trees` SET `name` = '敵意轉換' WHERE `skill_id` = '12';
UPDATE `skill_trees` SET `name` = '召喚攻城高崙' WHERE `skill_id` = '13';
UPDATE `skill_trees` SET `name` = '迷魅術' WHERE `skill_id` = '15';
UPDATE `skill_trees` SET `name` = '致命爆破' WHERE `skill_id` = '16';
UPDATE `skill_trees` SET `name` = '爆裂之力' WHERE `skill_id` = '17';
UPDATE `skill_trees` SET `name` = '強力挑撥' WHERE `skill_id` = '18';
UPDATE `skill_trees` SET `name` = '連環箭' WHERE `skill_id` = '19';
UPDATE `skill_trees` SET `name` = '解毒術' WHERE `skill_id` = '21';
UPDATE `skill_trees` SET `name` = '召喚吸血晶體' WHERE `skill_id` = '22';
UPDATE `skill_trees` SET `name` = '爆射箭' WHERE `skill_id` = '24';
UPDATE `skill_trees` SET `name` = '召喚機械高崙' WHERE `skill_id` = '25';
UPDATE `skill_trees` SET `name` = '開鎖' WHERE `skill_id` = '27';
UPDATE `skill_trees` SET `name` = '挑撥' WHERE `skill_id` = '28';
UPDATE `skill_trees` SET `name` = '鋼鐵之擊' WHERE `skill_id` = '29';
UPDATE `skill_trees` SET `name` = '背刺' WHERE `skill_id` = '30';
UPDATE `skill_trees` SET `name` = '召喚干擾晶體' WHERE `skill_id` = '33';
UPDATE `skill_trees` SET `name` = '包紮術' WHERE `skill_id` = '34';
UPDATE `skill_trees` SET `name` = '力量風暴' WHERE `skill_id` = '35';
UPDATE `skill_trees` SET `name` = '槍舞旋風' WHERE `skill_id` = '36';
UPDATE `skill_trees` SET `name` = '回收者' WHERE `skill_id` = '42';
UPDATE `skill_trees` SET `name` = '治療術' WHERE `skill_id` = '44';
UPDATE `skill_trees` SET `name` = '聖癒術' WHERE `skill_id` = '45';
UPDATE `skill_trees` SET `name` = '蒐集生命' WHERE `skill_id` = '46';
UPDATE `skill_trees` SET `name` = '怒雷風暴' WHERE `skill_id` = '48';
UPDATE `skill_trees` SET `name` = '神聖之擊' WHERE `skill_id` = '49';
UPDATE `skill_trees` SET `name` = '凝神聚氣' WHERE `skill_id` = '50';
UPDATE `skill_trees` SET `name` = '引誘' WHERE `skill_id` = '51';
UPDATE `skill_trees` SET `name` = '爆裂衝擊' WHERE `skill_id` = '54';
UPDATE `skill_trees` SET `name` = '能量箭' WHERE `skill_id` = '56';
UPDATE `skill_trees` SET `name` = '元素治癒' WHERE `skill_id` = '58';
UPDATE `skill_trees` SET `name` = '假死' WHERE `skill_id` = '60';
UPDATE `skill_trees` SET `name` = '止血術' WHERE `skill_id` = '61';
UPDATE `skill_trees` SET `name` = '戰慄' WHERE `skill_id` = '65';
UPDATE `skill_trees` SET `name` = '召喚治癒晶體' WHERE `skill_id` = '67';
UPDATE `skill_trees` SET `name` = '獻祭' WHERE `skill_id` = '69';
UPDATE `skill_trees` SET `name` = '能量奪取' WHERE `skill_id` = '70';
UPDATE `skill_trees` SET `name` = '鋼鐵意志' WHERE `skill_id` = '72';
UPDATE `skill_trees` SET `name` = '蟲族剋星' WHERE `skill_id` = '75';
UPDATE `skill_trees` SET `name` = '熊之圖騰靈' WHERE `skill_id` = '76';
UPDATE `skill_trees` SET `name` = '攻擊強化' WHERE `skill_id` = '77';
UPDATE `skill_trees` SET `name` = '戰之狂嚎' WHERE `skill_id` = '78';
UPDATE `skill_trees` SET `name` = '怪獸剋星' WHERE `skill_id` = '80';
UPDATE `skill_trees` SET `name` = '破滅之擊' WHERE `skill_id` = '81';
UPDATE `skill_trees` SET `name` = '霸體' WHERE `skill_id` = '82';
UPDATE `skill_trees` SET `name` = '狼之圖騰靈' WHERE `skill_id` = '83';
UPDATE `skill_trees` SET `name` = '毒刃之舞' WHERE `skill_id` = '84';
UPDATE `skill_trees` SET `name` = '還擊' WHERE `skill_id` = '86';
UPDATE `skill_trees` SET `name` = '動物剋星' WHERE `skill_id` = '87';
UPDATE `skill_trees` SET `name` = '龍族剋星' WHERE `skill_id` = '88';
UPDATE `skill_trees` SET `name` = '防禦強化' WHERE `skill_id` = '91';
UPDATE `skill_trees` SET `name` = '衝擊盾' WHERE `skill_id` = '92';
UPDATE `skill_trees` SET `name` = '狂暴戰士' WHERE `skill_id` = '94';
UPDATE `skill_trees` SET `name` = '癱瘓術' WHERE `skill_id` = '95';
UPDATE `skill_trees` SET `name` = '出血術' WHERE `skill_id` = '96';
UPDATE `skill_trees` SET `name` = '神聖庇護' WHERE `skill_id` = '97';
UPDATE `skill_trees` SET `name` = '惶恐之劍' WHERE `skill_id` = '98';
UPDATE `skill_trees` SET `name` = '快速箭' WHERE `skill_id` = '99';
UPDATE `skill_trees` SET `name` = '昏迷之擊' WHERE `skill_id` = '100';
UPDATE `skill_trees` SET `name` = '衝擊箭' WHERE `skill_id` = '101';
UPDATE `skill_trees` SET `name` = '纏繞之足' WHERE `skill_id` = '102';
UPDATE `skill_trees` SET `name` = '屍疫' WHERE `skill_id` = '103';
UPDATE `skill_trees` SET `name` = '植物剋星' WHERE `skill_id` = '104';
UPDATE `skill_trees` SET `name` = '冰凍之擊' WHERE `skill_id` = '105';
UPDATE `skill_trees` SET `name` = '視覺遮蔽' WHERE `skill_id` = '106';
UPDATE `skill_trees` SET `name` = '神聖靈氣' WHERE `skill_id` = '107';
UPDATE `skill_trees` SET `name` = '食人魔圖騰靈' WHERE `skill_id` = '109';
UPDATE `skill_trees` SET `name` = '極限防禦' WHERE `skill_id` = '110';
UPDATE `skill_trees` SET `name` = '極限迴避' WHERE `skill_id` = '111';
UPDATE `skill_trees` SET `name` = '禦箭術' WHERE `skill_id` = '112';
UPDATE `skill_trees` SET `name` = '遠箭術' WHERE `skill_id` = '113';
UPDATE `skill_trees` SET `name` = '能量破壞' WHERE `skill_id` = '115';
UPDATE `skill_trees` SET `name` = '怒嚎' WHERE `skill_id` = '116';
UPDATE `skill_trees` SET `name` = '法師迅捷術' WHERE `skill_id` = '118';
UPDATE `skill_trees` SET `name` = '昏迷之拳' WHERE `skill_id` = '120';
UPDATE `skill_trees` SET `name` = '戰鬥咆哮' WHERE `skill_id` = '121';
UPDATE `skill_trees` SET `name` = '衰弱術' WHERE `skill_id` = '122';
UPDATE `skill_trees` SET `name` = '精神屏障' WHERE `skill_id` = '123';
UPDATE `skill_trees` SET `name` = '遲緩術' WHERE `skill_id` = '127';
UPDATE `skill_trees` SET `name` = '施毒術' WHERE `skill_id` = '129';
UPDATE `skill_trees` SET `name` = '顫慄激戰' WHERE `skill_id` = '130';
UPDATE `skill_trees` SET `name` = '鷹之眼' WHERE `skill_id` = '131';
UPDATE `skill_trees` SET `name` = '強化意志' WHERE `skill_id` = '134';
UPDATE `skill_trees` SET `name` = '致命機率' WHERE `skill_id` = '137';
UPDATE `skill_trees` SET `name` = '勇氣加護' WHERE `skill_id` = '139';
UPDATE `skill_trees` SET `name` = '精通武器' WHERE `skill_id` = '141';
UPDATE `skill_trees` SET `name` = '精通護甲' WHERE `skill_id` = '142';
UPDATE `skill_trees` SET `name` = '精通晶體召喚' WHERE `skill_id` = '143';
UPDATE `skill_trees` SET `name` = '精通二刀流' WHERE `skill_id` = '144';
UPDATE `skill_trees` SET `name` = '抗魔術' WHERE `skill_id` = '146';
UPDATE `skill_trees` SET `name` = '魔法抵抗' WHERE `skill_id` = '147';
UPDATE `skill_trees` SET `name` = '生命之原' WHERE `skill_id` = '148';
UPDATE `skill_trees` SET `name` = '負重強化' WHERE `skill_id` = '150';
UPDATE `skill_trees` SET `name` = '精通盾技' WHERE `skill_id` = '153';
UPDATE `skill_trees` SET `name` = '咒語吟唱' WHERE `skill_id` = '163';
UPDATE `skill_trees` SET `name` = '快速恢復' WHERE `skill_id` = '164';
UPDATE `skill_trees` SET `name` = '交易術' WHERE `skill_id` = '165';
UPDATE `skill_trees` SET `name` = '攻擊加速' WHERE `skill_id` = '168';
UPDATE `skill_trees` SET `name` = '移動加速' WHERE `skill_id` = '169';
UPDATE `skill_trees` SET `name` = '活躍生命' WHERE `skill_id` = '171';
UPDATE `skill_trees` SET `name` = '物品製作' WHERE `skill_id` = '172';
UPDATE `skill_trees` SET `name` = '特技精通' WHERE `skill_id` = '173';
UPDATE `skill_trees` SET `name` = '狂暴加護' WHERE `skill_id` = '176';
UPDATE `skill_trees` SET `name` = '再生術' WHERE `skill_id` = '181';
UPDATE `skill_trees` SET `name` = '致命侵襲' WHERE `skill_id` = '190';
UPDATE `skill_trees` SET `name` = '精神凝聚' WHERE `skill_id` = '191';
UPDATE `skill_trees` SET `name` = '致命威力' WHERE `skill_id` = '193';
UPDATE `skill_trees` SET `name` = '幸運之神' WHERE `skill_id` = '194';
UPDATE `skill_trees` SET `name` = '調息術' WHERE `skill_id` = '195';
UPDATE `skill_trees` SET `name` = '神聖之刃' WHERE `skill_id` = '196';
UPDATE `skill_trees` SET `name` = '神聖之衣' WHERE `skill_id` = '197';
UPDATE `skill_trees` SET `name` = '迴避提升' WHERE `skill_id` = '198';
UPDATE `skill_trees` SET `name` = '精通鈍器' WHERE `skill_id` = '205';
UPDATE `skill_trees` SET `name` = '精通弓術' WHERE `skill_id` = '208';
UPDATE `skill_trees` SET `name` = '精通匕首' WHERE `skill_id` = '209';
UPDATE `skill_trees` SET `name` = '精通拳技' WHERE `skill_id` = '210';
UPDATE `skill_trees` SET `name` = '生命強化' WHERE `skill_id` = '211';
UPDATE `skill_trees` SET `name` = '快速生命恢復' WHERE `skill_id` = '212';
UPDATE `skill_trees` SET `name` = '魔力強化' WHERE `skill_id` = '213';
UPDATE `skill_trees` SET `name` = '魔力恢復術' WHERE `skill_id` = '214';
UPDATE `skill_trees` SET `name` = '精通長戟' WHERE `skill_id` = '216';
UPDATE `skill_trees` SET `name` = '精通劍鈍兵器' WHERE `skill_id` = '217';
UPDATE `skill_trees` SET `name` = '靜行術' WHERE `skill_id` = '221';
UPDATE `skill_trees` SET `name` = '狂暴之拳' WHERE `skill_id` = '222';
UPDATE `skill_trees` SET `name` = '要害刺擊' WHERE `skill_id` = '223';
UPDATE `skill_trees` SET `name` = '迴避移動' WHERE `skill_id` = '225';
UPDATE `skill_trees` SET `name` = '緩和術' WHERE `skill_id` = '226';
UPDATE `skill_trees` SET `name` = '精通輕裝甲' WHERE `skill_id` = '227';
UPDATE `skill_trees` SET `name` = '快速施法' WHERE `skill_id` = '228';
UPDATE `skill_trees` SET `name` = '快速魔力恢復' WHERE `skill_id` = '229';
UPDATE `skill_trees` SET `name` = '疾風衝刺' WHERE `skill_id` = '230';
UPDATE `skill_trees` SET `name` = '精通重裝甲' WHERE `skill_id` = '231';
UPDATE `skill_trees` SET `name` = '精通重裝甲' WHERE `skill_id` = '232';
UPDATE `skill_trees` SET `name` = '精通輕裝甲' WHERE `skill_id` = '233';
UPDATE `skill_trees` SET `name` = '精通長袍' WHERE `skill_id` = '234';
UPDATE `skill_trees` SET `name` = '精通長袍' WHERE `skill_id` = '235';
UPDATE `skill_trees` SET `name` = '精通輕裝甲' WHERE `skill_id` = '236';
UPDATE `skill_trees` SET `name` = 'D級專家' WHERE `skill_id` = '239';
UPDATE `skill_trees` SET `name` = 'C級專家' WHERE `skill_id` = '239' AND `level` = '2';
UPDATE `skill_trees` SET `name` = 'B級專家' WHERE `skill_id` = '239' AND `level` = '3';
UPDATE `skill_trees` SET `name` = 'A級專家' WHERE `skill_id` = '239' AND `level` = '4';
UPDATE `skill_trees` SET `name` = 'S級專家' WHERE `skill_id` = '239' AND `level` = '5';
UPDATE `skill_trees` SET `name` = 'S80級專家' WHERE `skill_id` = '239' AND `level` = '6';
UPDATE `skill_trees` SET `name` = '精通護甲' WHERE `skill_id` = '244';
UPDATE `skill_trees` SET `name` = '瘋狂掃蕩' WHERE `skill_id` = '245';
UPDATE `skill_trees` SET `name` = '統治者封印' WHERE `skill_id` = '246';
UPDATE `skill_trees` SET `name` = '攻城陣地' WHERE `skill_id` = '247';
UPDATE `skill_trees` SET `name` = '結晶製作' WHERE `skill_id` = '248';
UPDATE `skill_trees` SET `name` = '精通武器' WHERE `skill_id` = '249';
UPDATE `skill_trees` SET `name` = '精通武器' WHERE `skill_id` = '250';
UPDATE `skill_trees` SET `name` = '精通長袍' WHERE `skill_id` = '251';
UPDATE `skill_trees` SET `name` = '精通輕裝甲' WHERE `skill_id` = '252';
UPDATE `skill_trees` SET `name` = '精通重裝甲' WHERE `skill_id` = '253';
UPDATE `skill_trees` SET `name` = '自體變化' WHERE `skill_id` = '254';
UPDATE `skill_trees` SET `name` = '能量破擊' WHERE `skill_id` = '255';
UPDATE `skill_trees` SET `name` = '精準目標' WHERE `skill_id` = '256';
UPDATE `skill_trees` SET `name` = '精通劍鈍兵器' WHERE `skill_id` = '257';
UPDATE `skill_trees` SET `name` = '精通輕裝甲' WHERE `skill_id` = '258';
UPDATE `skill_trees` SET `name` = '精通重裝甲' WHERE `skill_id` = '259';
UPDATE `skill_trees` SET `name` = '昏迷衝擊' WHERE `skill_id` = '260';
UPDATE `skill_trees` SET `name` = '波動三連斬' WHERE `skill_id` = '261';
UPDATE `skill_trees` SET `name` = '神聖祝福' WHERE `skill_id` = '262';
UPDATE `skill_trees` SET `name` = '致命之息' WHERE `skill_id` = '263';
UPDATE `skill_trees` SET `name` = '大地之歌' WHERE `skill_id` = '264';
UPDATE `skill_trees` SET `name` = '生命之歌' WHERE `skill_id` = '265';
UPDATE `skill_trees` SET `name` = '水靈之歌' WHERE `skill_id` = '266';
UPDATE `skill_trees` SET `name` = '護衛之歌' WHERE `skill_id` = '267';
UPDATE `skill_trees` SET `name` = '風靈之歌' WHERE `skill_id` = '268';
UPDATE `skill_trees` SET `name` = '獵者之歌' WHERE `skill_id` = '269';
UPDATE `skill_trees` SET `name` = '祈願之歌' WHERE `skill_id` = '270';
UPDATE `skill_trees` SET `name` = '戰士之舞' WHERE `skill_id` = '271';
UPDATE `skill_trees` SET `name` = '士氣之舞' WHERE `skill_id` = '272';
UPDATE `skill_trees` SET `name` = '神祕之舞' WHERE `skill_id` = '273';
UPDATE `skill_trees` SET `name` = '火靈之舞' WHERE `skill_id` = '274';
UPDATE `skill_trees` SET `name` = '狂暴之舞' WHERE `skill_id` = '275';
UPDATE `skill_trees` SET `name` = '專注之舞' WHERE `skill_id` = '276';
UPDATE `skill_trees` SET `name` = '光耀之舞' WHERE `skill_id` = '277';
UPDATE `skill_trees` SET `name` = '召喚毒蛇晶體' WHERE `skill_id` = '278';
UPDATE `skill_trees` SET `name` = '怒雷強擊' WHERE `skill_id` = '279';
UPDATE `skill_trees` SET `name` = '赤燄之拳' WHERE `skill_id` = '280';
UPDATE `skill_trees` SET `name` = '破滅靈魂' WHERE `skill_id` = '281';
UPDATE `skill_trees` SET `name` = '豹之圖騰靈' WHERE `skill_id` = '282';
UPDATE `skill_trees` SET `name` = '召喚黑暗豹' WHERE `skill_id` = '283';
UPDATE `skill_trees` SET `name` = '風暴之擊' WHERE `skill_id` = '284';
UPDATE `skill_trees` SET `name` = '強效魔力回復' WHERE `skill_id` = '285';
UPDATE `skill_trees` SET `name` = '激怒' WHERE `skill_id` = '286';
UPDATE `skill_trees` SET `name` = '獅子之心' WHERE `skill_id` = '287';
UPDATE `skill_trees` SET `name` = '警戒狀態' WHERE `skill_id` = '288';
UPDATE `skill_trees` SET `name` = '生命吸取' WHERE `skill_id` = '289';
UPDATE `skill_trees` SET `name` = '最終狂擊' WHERE `skill_id` = '290';
UPDATE `skill_trees` SET `name` = '最終要塞' WHERE `skill_id` = '291';
UPDATE `skill_trees` SET `name` = '野牛圖騰靈' WHERE `skill_id` = '292';
UPDATE `skill_trees` SET `name` = '精通雙手武器' WHERE `skill_id` = '293';
UPDATE `skill_trees` SET `name` = '暗影感識' WHERE `skill_id` = '294';
UPDATE `skill_trees` SET `name` = '剛體' WHERE `skill_id` = '295';
UPDATE `skill_trees` SET `name` = '變色龍潛息' WHERE `skill_id` = '296';
UPDATE `skill_trees` SET `name` = '決鬥者之靈' WHERE `skill_id` = '297';
UPDATE `skill_trees` SET `name` = '兔子圖騰靈' WHERE `skill_id` = '298';
UPDATE `skill_trees` SET `name` = '召喚野豬加農砲' WHERE `skill_id` = '299';
UPDATE `skill_trees` SET `name` = '召喚大炸彈' WHERE `skill_id` = '301';
UPDATE `skill_trees` SET `name` = '自體變化慶典' WHERE `skill_id` = '302';
UPDATE `skill_trees` SET `name` = '射手座之魂' WHERE `skill_id` = '303';
UPDATE `skill_trees` SET `name` = '勝利之歌' WHERE `skill_id` = '304';
UPDATE `skill_trees` SET `name` = '復仇之歌' WHERE `skill_id` = '305';
UPDATE `skill_trees` SET `name` = '抗火之歌' WHERE `skill_id` = '306';
UPDATE `skill_trees` SET `name` = '抗水之舞' WHERE `skill_id` = '307';
UPDATE `skill_trees` SET `name` = '抗風之歌' WHERE `skill_id` = '308';
UPDATE `skill_trees` SET `name` = '抗地之舞' WHERE `skill_id` = '309';
UPDATE `skill_trees` SET `name` = '吸血之舞' WHERE `skill_id` = '310';
UPDATE `skill_trees` SET `name` = '保護之舞' WHERE `skill_id` = '311';
UPDATE `skill_trees` SET `name` = '痛擊之勢' WHERE `skill_id` = '312';
UPDATE `skill_trees` SET `name` = '狙擊' WHERE `skill_id` = '313';
UPDATE `skill_trees` SET `name` = '致命反擊' WHERE `skill_id` = '314';
UPDATE `skill_trees` SET `name` = '破滅爆碎' WHERE `skill_id` = '315';
UPDATE `skill_trees` SET `name` = '庇護' WHERE `skill_id` = '316';
UPDATE `skill_trees` SET `name` = '專注攻擊' WHERE `skill_id` = '317';
UPDATE `skill_trees` SET `name` = '庇護之勢' WHERE `skill_id` = '318';
UPDATE `skill_trees` SET `name` = '身手輕靈' WHERE `skill_id` = '319';
UPDATE `skill_trees` SET `name` = '憤怒' WHERE `skill_id` = '320';
UPDATE `skill_trees` SET `name` = '昏眩爆破' WHERE `skill_id` = '321';
UPDATE `skill_trees` SET `name` = '保護要塞' WHERE `skill_id` = '322';
UPDATE `skill_trees` SET `name` = '矢之顫聲-A級' WHERE `skill_id` = '323';
UPDATE `skill_trees` SET `name` = '矢之顫聲-S級' WHERE `skill_id` = '324';
UPDATE `skill_trees` SET `name` = '座龍攻城強襲' WHERE `skill_id` = '325';
UPDATE `skill_trees` SET `name` = '高級攻城陣地' WHERE `skill_id` = '326';
UPDATE `skill_trees` SET `name` = '飛龍護盾' WHERE `skill_id` = '327';
UPDATE `skill_trees` SET `name` = '睿智' WHERE `skill_id` = '328';
UPDATE `skill_trees` SET `name` = '健壯' WHERE `skill_id` = '329';
UPDATE `skill_trees` SET `name` = '精通戰技' WHERE `skill_id` = '330';
UPDATE `skill_trees` SET `name` = '精通魔法' WHERE `skill_id` = '331';
UPDATE `skill_trees` SET `name` = '擴充包袱' WHERE `skill_id` = '332';
UPDATE `skill_trees` SET `name` = '擴充販賣數量' WHERE `skill_id` = '333';
UPDATE `skill_trees` SET `name` = '精通極致技能' WHERE `skill_id` = '334';
UPDATE `skill_trees` SET `name` = '剛毅' WHERE `skill_id` = '335';
UPDATE `skill_trees` SET `name` = '智慧的奧祕' WHERE `skill_id` = '336';
UPDATE `skill_trees` SET `name` = '力量的奧祕' WHERE `skill_id` = '337';
UPDATE `skill_trees` SET `name` = '靈思的奧祕' WHERE `skill_id` = '338';
UPDATE `skill_trees` SET `name` = '格擋狀態' WHERE `skill_id` = '339';
UPDATE `skill_trees` SET `name` = '反擊狀態' WHERE `skill_id` = '340';
UPDATE `skill_trees` SET `name` = '生命的觸動' WHERE `skill_id` = '341';
UPDATE `skill_trees` SET `name` = '死亡的觸動' WHERE `skill_id` = '342';
UPDATE `skill_trees` SET `name` = '斷魂箭' WHERE `skill_id` = '343';
UPDATE `skill_trees` SET `name` = '亡命一擊' WHERE `skill_id` = '344';
UPDATE `skill_trees` SET `name` = '波動劍震' WHERE `skill_id` = '345';
UPDATE `skill_trees` SET `name` = '鬥拳氣破' WHERE `skill_id` = '346';
UPDATE `skill_trees` SET `name` = '烈震閃' WHERE `skill_id` = '347';
UPDATE `skill_trees` SET `name` = '自體崩壞' WHERE `skill_id` = '348';
UPDATE `skill_trees` SET `name` = '奮迅之歌' WHERE `skill_id` = '349';
UPDATE `skill_trees` SET `name` = '物理鏡射' WHERE `skill_id` = '350';
UPDATE `skill_trees` SET `name` = '魔法鏡射' WHERE `skill_id` = '351';
UPDATE `skill_trees` SET `name` = '重擊盾' WHERE `skill_id` = '352';
UPDATE `skill_trees` SET `name` = '猛擊盾' WHERE `skill_id` = '353';
UPDATE `skill_trees` SET `name` = '制動之射' WHERE `skill_id` = '354';
UPDATE `skill_trees` SET `name` = '死亡背擊' WHERE `skill_id` = '355';
UPDATE `skill_trees` SET `name` = '殺機' WHERE `skill_id` = '356';
UPDATE `skill_trees` SET `name` = '殺意' WHERE `skill_id` = '357';
UPDATE `skill_trees` SET `name` = '愚弄' WHERE `skill_id` = '358';
UPDATE `skill_trees` SET `name` = '狩者之眼' WHERE `skill_id` = '359';
UPDATE `skill_trees` SET `name` = '殺手之眼' WHERE `skill_id` = '360';
UPDATE `skill_trees` SET `name` = '破心衝' WHERE `skill_id` = '361';
UPDATE `skill_trees` SET `name` = '破甲壞擊' WHERE `skill_id` = '362';
UPDATE `skill_trees` SET `name` = '沉思之歌' WHERE `skill_id` = '363';
UPDATE `skill_trees` SET `name` = '鬥者之歌' WHERE `skill_id` = '364';
UPDATE `skill_trees` SET `name` = '艷惑之舞' WHERE `skill_id` = '365';
UPDATE `skill_trees` SET `name` = '闇影之舞' WHERE `skill_id` = '366';
UPDATE `skill_trees` SET `name` = '梅杜莎之舞' WHERE `skill_id` = '367';
UPDATE `skill_trees` SET `name` = '復仇' WHERE `skill_id` = '368';
UPDATE `skill_trees` SET `name` = '迴避射擊' WHERE `skill_id` = '369';
UPDATE `skill_trees` SET `name` = '盟誓-血盟體魄' WHERE `skill_id` = '370';
UPDATE `skill_trees` SET `name` = '盟誓-血盟精神' WHERE `skill_id` = '371';
UPDATE `skill_trees` SET `name` = '盟誓-血盟靈魂' WHERE `skill_id` = '372';
UPDATE `skill_trees` SET `name` = '盟誓-奮戰不懈' WHERE `skill_id` = '373';
UPDATE `skill_trees` SET `name` = '盟誓-士氣高昂' WHERE `skill_id` = '374';
UPDATE `skill_trees` SET `name` = '盟誓-沉著冷靜' WHERE `skill_id` = '375';
UPDATE `skill_trees` SET `name` = '盟誓-威猛剛健' WHERE `skill_id` = '376';
UPDATE `skill_trees` SET `name` = '盟誓-堅定不移' WHERE `skill_id` = '377';
UPDATE `skill_trees` SET `name` = '盟誓-英明睿智' WHERE `skill_id` = '378';
UPDATE `skill_trees` SET `name` = '盟誓-鋼鐵意志' WHERE `skill_id` = '379';
UPDATE `skill_trees` SET `name` = '盟誓-將士用命' WHERE `skill_id` = '380';
UPDATE `skill_trees` SET `name` = '盟誓-謀定後動' WHERE `skill_id` = '381';
UPDATE `skill_trees` SET `name` = '盟誓-騎士精神' WHERE `skill_id` = '382';
UPDATE `skill_trees` SET `name` = '盟誓-騎士榮耀' WHERE `skill_id` = '383';
UPDATE `skill_trees` SET `name` = '盟誓-風雨無阻' WHERE `skill_id` = '384';
UPDATE `skill_trees` SET `name` = '盟誓-百鍊成鋼' WHERE `skill_id` = '385';
UPDATE `skill_trees` SET `name` = '盟誓-威武不屈' WHERE `skill_id` = '386';
UPDATE `skill_trees` SET `name` = '盟誓-勇往直前' WHERE `skill_id` = '387';
UPDATE `skill_trees` SET `name` = '盟誓-盡忠職守' WHERE `skill_id` = '388';
UPDATE `skill_trees` SET `name` = '盟誓-兵貴神速' WHERE `skill_id` = '389';
UPDATE `skill_trees` SET `name` = '盟誓-鞠躬盡瘁' WHERE `skill_id` = '390';
UPDATE `skill_trees` SET `name` = '盟誓-帝權授命' WHERE `skill_id` = '391';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '392';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '393';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '394';
UPDATE `skill_trees` SET `name` = '英雄的奇蹟' WHERE `skill_id` = '395';
UPDATE `skill_trees` SET `name` = '英雄的狂熱' WHERE `skill_id` = '396';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '397';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '398';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '399';
UPDATE `skill_trees` SET `name` = '裁決' WHERE `skill_id` = '400';
UPDATE `skill_trees` SET `name` = '審判' WHERE `skill_id` = '401';
UPDATE `skill_trees` SET `name` = '逮捕' WHERE `skill_id` = '402';
UPDATE `skill_trees` SET `name` = '拘束' WHERE `skill_id` = '403';
UPDATE `skill_trees` SET `name` = '群體拘束' WHERE `skill_id` = '404';
UPDATE `skill_trees` SET `name` = '退魔' WHERE `skill_id` = '405';
UPDATE `skill_trees` SET `name` = '天使聖靈' WHERE `skill_id` = '406';
UPDATE `skill_trees` SET `name` = '精神交響曲' WHERE `skill_id` = '407';
UPDATE `skill_trees` SET `name` = '魔刃之舞' WHERE `skill_id` = '408';
UPDATE `skill_trees` SET `name` = '會心一擊' WHERE `skill_id` = '409';
UPDATE `skill_trees` SET `name` = '殺念' WHERE `skill_id` = '410';
UPDATE `skill_trees` SET `name` = '匿蹤' WHERE `skill_id` = '411';
UPDATE `skill_trees` SET `name` = '沙塵' WHERE `skill_id` = '412';
UPDATE `skill_trees` SET `name` = '火速疾射' WHERE `skill_id` = '413';
UPDATE `skill_trees` SET `name` = '死亡凝視' WHERE `skill_id` = '414';
UPDATE `skill_trees` SET `name` = '射手座精神' WHERE `skill_id` = '415';
UPDATE `skill_trees` SET `name` = '射手座祝福' WHERE `skill_id` = '416';
UPDATE `skill_trees` SET `name` = '射手座苦痛' WHERE `skill_id` = '417';
UPDATE `skill_trees` SET `name` = '箭袋' WHERE `skill_id` = '418';
UPDATE `skill_trees` SET `name` = '召喚寶箱鑰匙' WHERE `skill_id` = '419';
UPDATE `skill_trees` SET `name` = '狂信者' WHERE `skill_id` = '420';
UPDATE `skill_trees` SET `name` = '闊擊' WHERE `skill_id` = '421';
UPDATE `skill_trees` SET `name` = '精準槍技' WHERE `skill_id` = '422';
UPDATE `skill_trees` SET `name` = '煉獄之體' WHERE `skill_id` = '423';
UPDATE `skill_trees` SET `name` = '戰爭狂熱' WHERE `skill_id` = '424';
UPDATE `skill_trees` SET `name` = '獵鷹圖騰靈' WHERE `skill_id` = '425';
UPDATE `skill_trees` SET `name` = '戰鬥態勢' WHERE `skill_id` = '426';
UPDATE `skill_trees` SET `name` = '誦咒態勢' WHERE `skill_id` = '427';
UPDATE `skill_trees` SET `name` = '自我韻律' WHERE `skill_id` = '428';
UPDATE `skill_trees` SET `name` = '騎士精神' WHERE `skill_id` = '429';
UPDATE `skill_trees` SET `name` = '格鬥大師' WHERE `skill_id` = '430';
UPDATE `skill_trees` SET `name` = '射日' WHERE `skill_id` = '431';
UPDATE `skill_trees` SET `name` = '殺手本能' WHERE `skill_id` = '432';
UPDATE `skill_trees` SET `name` = '奧祕律法' WHERE `skill_id` = '433';
UPDATE `skill_trees` SET `name` = '降靈祕術' WHERE `skill_id` = '434';
UPDATE `skill_trees` SET `name` = '召喚權能' WHERE `skill_id` = '435';
UPDATE `skill_trees` SET `name` = '神聖真知' WHERE `skill_id` = '436';
UPDATE `skill_trees` SET `name` = '寂靜之歌' WHERE `skill_id` = '437';
UPDATE `skill_trees` SET `name` = '不死鳥之魂' WHERE `skill_id` = '438';
UPDATE `skill_trees` SET `name` = '復仇護盾' WHERE `skill_id` = '439';
UPDATE `skill_trees` SET `name` = '勇者之心' WHERE `skill_id` = '440';
UPDATE `skill_trees` SET `name` = '無想鬥魂' WHERE `skill_id` = '441';
UPDATE `skill_trees` SET `name` = '波動氣場' WHERE `skill_id` = '442';
UPDATE `skill_trees` SET `name` = '鬥氣障壁' WHERE `skill_id` = '443';
UPDATE `skill_trees` SET `name` = '回收者慶典' WHERE `skill_id` = '444';
UPDATE `skill_trees` SET `name` = '海市蜃樓' WHERE `skill_id` = '445';
UPDATE `skill_trees` SET `name` = '閃避態勢' WHERE `skill_id` = '446';
UPDATE `skill_trees` SET `name` = '反擊態勢' WHERE `skill_id` = '447';
UPDATE `skill_trees` SET `name` = '召喚奇襲加農砲' WHERE `skill_id` = '448';
UPDATE `skill_trees` SET `name` = '召喚吸引晶體' WHERE `skill_id` = '449';
UPDATE `skill_trees` SET `name` = '弒神' WHERE `skill_id` = '450';
UPDATE `skill_trees` SET `name` = '波動疾行' WHERE `skill_id` = '451';
UPDATE `skill_trees` SET `name` = '奔雷腳' WHERE `skill_id` = '452';
UPDATE `skill_trees` SET `name` = '逃脫術' WHERE `skill_id` = '453';
UPDATE `skill_trees` SET `name` = '鐵壁陣勢' WHERE `skill_id` = '454';
UPDATE `skill_trees` SET `name` = '高歌陣勢' WHERE `skill_id` = '455';
UPDATE `skill_trees` SET `name` = '剛毅陣勢' WHERE `skill_id` = '456';
UPDATE `skill_trees` SET `name` = '奮戰陣勢' WHERE `skill_id` = '457';
UPDATE `skill_trees` SET `name` = '激鬥陣勢' WHERE `skill_id` = '458';
UPDATE `skill_trees` SET `name` = '狙擊陣勢' WHERE `skill_id` = '459';
UPDATE `skill_trees` SET `name` = '暗殺陣勢' WHERE `skill_id` = '460';
UPDATE `skill_trees` SET `name` = '鬥氣爆發' WHERE `skill_id` = '461';
UPDATE `skill_trees` SET `name` = '罪體' WHERE `skill_id` = '462';
UPDATE `skill_trees` SET `name` = '精通武器' WHERE `skill_id` = '463';
UPDATE `skill_trees` SET `name` = '精通護甲' WHERE `skill_id` = '464';
UPDATE `skill_trees` SET `name` = '精通輕裝甲' WHERE `skill_id` = '465';
UPDATE `skill_trees` SET `name` = '魔法免疫' WHERE `skill_id` = '466';
UPDATE `skill_trees` SET `name` = '精通魂魄' WHERE `skill_id` = '467';
UPDATE `skill_trees` SET `name` = '墮落之擊' WHERE `skill_id` = '468';
UPDATE `skill_trees` SET `name` = '火速攻擊' WHERE `skill_id` = '469';
UPDATE `skill_trees` SET `name` = '察覺陷阱' WHERE `skill_id` = '470';
UPDATE `skill_trees` SET `name` = '拆除陷阱' WHERE `skill_id` = '471';
UPDATE `skill_trees` SET `name` = '精通古代劍' WHERE `skill_id` = '472';
UPDATE `skill_trees` SET `name` = '精通弩箭' WHERE `skill_id` = '473';
UPDATE `skill_trees` SET `name` = '精通細劍' WHERE `skill_id` = '474';
UPDATE `skill_trees` SET `name` = '返還之擊' WHERE `skill_id` = '475';
UPDATE `skill_trees` SET `name` = '黑暗之擊' WHERE `skill_id` = '476';
UPDATE `skill_trees` SET `name` = '黑暗破擊' WHERE `skill_id` = '477';
UPDATE `skill_trees` SET `name` = '二連刺' WHERE `skill_id` = '478';
UPDATE `skill_trees` SET `name` = '急行軍' WHERE `skill_id` = '479';
UPDATE `skill_trees` SET `name` = '黑暗之刃' WHERE `skill_id` = '480';
UPDATE `skill_trees` SET `name` = '黑暗裝甲' WHERE `skill_id` = '481';
UPDATE `skill_trees` SET `name` = '暴怒之魂' WHERE `skill_id` = '482';
UPDATE `skill_trees` SET `name` = '劍盾' WHERE `skill_id` = '483';
UPDATE `skill_trees` SET `name` = '疾襲' WHERE `skill_id` = '484';
UPDATE `skill_trees` SET `name` = '卸除武器' WHERE `skill_id` = '485';
UPDATE `skill_trees` SET `name` = '範圍加持' WHERE `skill_id` = '486';
UPDATE `skill_trees` SET `name` = '刺入射擊' WHERE `skill_id` = '487';
UPDATE `skill_trees` SET `name` = '變換目標' WHERE `skill_id` = '489';
UPDATE `skill_trees` SET `name` = '快速射擊' WHERE `skill_id` = '490';
UPDATE `skill_trees` SET `name` = '不使用' WHERE `skill_id` = '491';
UPDATE `skill_trees` SET `name` = '展翅' WHERE `skill_id` = '492';
UPDATE `skill_trees` SET `name` = '風暴強襲' WHERE `skill_id` = '493';
UPDATE `skill_trees` SET `name` = '肩部突擊' WHERE `skill_id` = '494';
UPDATE `skill_trees` SET `name` = '刀刃亂舞' WHERE `skill_id` = '495';
UPDATE `skill_trees` SET `name` = '刀刃連斬' WHERE `skill_id` = '496';
UPDATE `skill_trees` SET `name` = '劇痛碎擊' WHERE `skill_id` = '497';
UPDATE `skill_trees` SET `name` = '迸裂' WHERE `skill_id` = '498';
UPDATE `skill_trees` SET `name` = '勇氣' WHERE `skill_id` = '499';
UPDATE `skill_trees` SET `name` = '真 狂戰士' WHERE `skill_id` = '500';
UPDATE `skill_trees` SET `name` = '暴戾之氣' WHERE `skill_id` = '501';
UPDATE `skill_trees` SET `name` = '生命轉魂' WHERE `skill_id` = '502';
UPDATE `skill_trees` SET `name` = '輕蔑' WHERE `skill_id` = '503';
UPDATE `skill_trees` SET `name` = '三連刺' WHERE `skill_id` = '504';
UPDATE `skill_trees` SET `name` = '閃耀之鋒' WHERE `skill_id` = '505';
UPDATE `skill_trees` SET `name` = '擊潰' WHERE `skill_id` = '506';
UPDATE `skill_trees` SET `name` = '雙重射擊' WHERE `skill_id` = '507';
UPDATE `skill_trees` SET `name` = '上衝射擊' WHERE `skill_id` = '508';
UPDATE `skill_trees` SET `name` = '出血射擊' WHERE `skill_id` = '509';
UPDATE `skill_trees` SET `name` = '致命輪盤' WHERE `skill_id` = '510';
UPDATE `skill_trees` SET `name` = '誘惑' WHERE `skill_id` = '511';
UPDATE `skill_trees` SET `name` = '製作生物藥劑' WHERE `skill_id` = '512';
UPDATE `skill_trees` SET `name` = '製作黑暗種子' WHERE `skill_id` = '513';
UPDATE `skill_trees` SET `name` = '火陷阱' WHERE `skill_id` = '514';
UPDATE `skill_trees` SET `name` = '毒陷阱' WHERE `skill_id` = '515';
UPDATE `skill_trees` SET `name` = '緩速陷阱' WHERE `skill_id` = '516';
UPDATE `skill_trees` SET `name` = '閃光陷阱' WHERE `skill_id` = '517';
UPDATE `skill_trees` SET `name` = '約束陷阱' WHERE `skill_id` = '518';
UPDATE `skill_trees` SET `name` = '弩箭筒-A級' WHERE `skill_id` = '519';
UPDATE `skill_trees` SET `name` = '弩箭筒-S級' WHERE `skill_id` = '520';
UPDATE `skill_trees` SET `name` = '精銳射擊' WHERE `skill_id` = '521';
UPDATE `skill_trees` SET `name` = '真實目標' WHERE `skill_id` = '522';
UPDATE `skill_trees` SET `name` = '植入黑暗種子' WHERE `skill_id` = '523';
UPDATE `skill_trees` SET `name` = '治療黑暗種子' WHERE `skill_id` = '524';
UPDATE `skill_trees` SET `name` = '誘餌' WHERE `skill_id` = '525';
UPDATE `skill_trees` SET `name` = '諸天之上' WHERE `skill_id` = '526';
UPDATE `skill_trees` SET `name` = '鐵之盾' WHERE `skill_id` = '527';
UPDATE `skill_trees` SET `name` = '信念之盾' WHERE `skill_id` = '528';
UPDATE `skill_trees` SET `name` = '元素之歌' WHERE `skill_id` = '529';
UPDATE `skill_trees` SET `name` = '團結之舞' WHERE `skill_id` = '530';
UPDATE `skill_trees` SET `name` = '爆擊之痕' WHERE `skill_id` = '531';
UPDATE `skill_trees` SET `name` = '反擊契機' WHERE `skill_id` = '532';
UPDATE `skill_trees` SET `name` = '反擊快速箭' WHERE `skill_id` = '533';
UPDATE `skill_trees` SET `name` = '反擊衝刺' WHERE `skill_id` = '534';
UPDATE `skill_trees` SET `name` = '反擊心靈' WHERE `skill_id` = '535';
UPDATE `skill_trees` SET `name` = '超越之體' WHERE `skill_id` = '536';
UPDATE `skill_trees` SET `name` = '變質炸彈' WHERE `skill_id` = '537';
UPDATE `skill_trees` SET `name` = '最終形體' WHERE `skill_id` = '538';
UPDATE `skill_trees` SET `name` = '爪攻擊' WHERE `skill_id` = '539';
UPDATE `skill_trees` SET `name` = '展翼強襲' WHERE `skill_id` = '540';
UPDATE `skill_trees` SET `name` = '變身 門徒聖杯' WHERE `skill_id` = '541';
UPDATE `skill_trees` SET `name` = '變身 門徒聖杯' WHERE `skill_id` = '542';
UPDATE `skill_trees` SET `name` = '變身 門徒聖杯' WHERE `skill_id` = '543';
UPDATE `skill_trees` SET `name` = '變身 獨角獸' WHERE `skill_id` = '544';
UPDATE `skill_trees` SET `name` = '變身 獨角獸' WHERE `skill_id` = '545';
UPDATE `skill_trees` SET `name` = '變身 獨角獸' WHERE `skill_id` = '546';
UPDATE `skill_trees` SET `name` = '變身 莉莉恩騎士' WHERE `skill_id` = '547';
UPDATE `skill_trees` SET `name` = '變身 莉莉恩騎士' WHERE `skill_id` = '548';
UPDATE `skill_trees` SET `name` = '變身 莉莉恩騎士' WHERE `skill_id` = '549';
UPDATE `skill_trees` SET `name` = '變身 高崙守護者' WHERE `skill_id` = '550';
UPDATE `skill_trees` SET `name` = '變身 高崙守護者' WHERE `skill_id` = '551';
UPDATE `skill_trees` SET `name` = '變身 高崙守護者' WHERE `skill_id` = '552';
UPDATE `skill_trees` SET `name` = '變身 煉獄龍獸' WHERE `skill_id` = '553';
UPDATE `skill_trees` SET `name` = '變身 煉獄龍獸' WHERE `skill_id` = '554';
UPDATE `skill_trees` SET `name` = '變身 煉獄龍獸' WHERE `skill_id` = '555';
UPDATE `skill_trees` SET `name` = '變身 暴烈龍' WHERE `skill_id` = '556';
UPDATE `skill_trees` SET `name` = '變身 暴烈龍' WHERE `skill_id` = '557';
UPDATE `skill_trees` SET `name` = '變身 暴烈龍' WHERE `skill_id` = '558';
UPDATE `skill_trees` SET `name` = '矛' WHERE `skill_id` = '559';
UPDATE `skill_trees` SET `name` = '強力斬' WHERE `skill_id` = '560';
UPDATE `skill_trees` SET `name` = '天使的祝福' WHERE `skill_id` = '561';
UPDATE `skill_trees` SET `name` = '天使之風' WHERE `skill_id` = '562';
UPDATE `skill_trees` SET `name` = '末日之角' WHERE `skill_id` = '563';
UPDATE `skill_trees` SET `name` = '重力控制' WHERE `skill_id` = '564';
UPDATE `skill_trees` SET `name` = '強襲之角' WHERE `skill_id` = '565';
UPDATE `skill_trees` SET `name` = '治癒之光' WHERE `skill_id` = '567';
UPDATE `skill_trees` SET `name` = '攻擊爆破' WHERE `skill_id` = '568';
UPDATE `skill_trees` SET `name` = '攻擊風暴' WHERE `skill_id` = '569';
UPDATE `skill_trees` SET `name` = '攻擊暴怒' WHERE `skill_id` = '570';
UPDATE `skill_trees` SET `name` = '毒粉末' WHERE `skill_id` = '571';
UPDATE `skill_trees` SET `name` = '雙斬' WHERE `skill_id` = '572';
UPDATE `skill_trees` SET `name` = '烈震閃' WHERE `skill_id` = '573';
UPDATE `skill_trees` SET `name` = '安裝炸彈' WHERE `skill_id` = '574';
UPDATE `skill_trees` SET `name` = '鋼刃殺' WHERE `skill_id` = '575';
UPDATE `skill_trees` SET `name` = '前腿強擊' WHERE `skill_id` = '576';
UPDATE `skill_trees` SET `name` = '火焰氣息' WHERE `skill_id` = '577';
UPDATE `skill_trees` SET `name` = '火焰震憾' WHERE `skill_id` = '578';
UPDATE `skill_trees` SET `name` = '火焰裝甲' WHERE `skill_id` = '579';
UPDATE `skill_trees` SET `name` = '死亡爆破' WHERE `skill_id` = '580';
UPDATE `skill_trees` SET `name` = '砂雲' WHERE `skill_id` = '581';
UPDATE `skill_trees` SET `name` = '領域出血' WHERE `skill_id` = '582';
UPDATE `skill_trees` SET `name` = '同化' WHERE `skill_id` = '583';
UPDATE `skill_trees` SET `name` = '強力之爪' WHERE `skill_id` = '584';
UPDATE `skill_trees` SET `name` = '快速移動' WHERE `skill_id` = '585';
UPDATE `skill_trees` SET `name` = '旋轉攻擊' WHERE `skill_id` = '586';
UPDATE `skill_trees` SET `name` = '刺掘攻擊' WHERE `skill_id` = '587';
UPDATE `skill_trees` SET `name` = '幽暗咀咒' WHERE `skill_id` = '588';
UPDATE `skill_trees` SET `name` = '幽暗能量吸收' WHERE `skill_id` = '589';
UPDATE `skill_trees` SET `name` = '居所-體魄' WHERE `skill_id` = '590';
UPDATE `skill_trees` SET `name` = '居所-精神' WHERE `skill_id` = '591';
UPDATE `skill_trees` SET `name` = '居所-靈魂' WHERE `skill_id` = '592';
UPDATE `skill_trees` SET `name` = '居所-奮戰不懈' WHERE `skill_id` = '593';
UPDATE `skill_trees` SET `name` = '居所-士氣高昂' WHERE `skill_id` = '594';
UPDATE `skill_trees` SET `name` = '居所-沉著冷靜' WHERE `skill_id` = '595';
UPDATE `skill_trees` SET `name` = '居所-威猛剛健' WHERE `skill_id` = '596';
UPDATE `skill_trees` SET `name` = '居所-堅定不移' WHERE `skill_id` = '597';
UPDATE `skill_trees` SET `name` = '居所-英明睿智' WHERE `skill_id` = '598';
UPDATE `skill_trees` SET `name` = '居所-鋼鐵意志' WHERE `skill_id` = '599';
UPDATE `skill_trees` SET `name` = '居所-將士用命' WHERE `skill_id` = '600';
UPDATE `skill_trees` SET `name` = '居所-謀定後動' WHERE `skill_id` = '601';
UPDATE `skill_trees` SET `name` = '居所-騎士精神' WHERE `skill_id` = '602';
UPDATE `skill_trees` SET `name` = '居所-騎士榮耀' WHERE `skill_id` = '603';
UPDATE `skill_trees` SET `name` = '居所-風雨無阻' WHERE `skill_id` = '604';
UPDATE `skill_trees` SET `name` = '居所-百鍊成鋼' WHERE `skill_id` = '605';
UPDATE `skill_trees` SET `name` = '居所-威武不屈' WHERE `skill_id` = '606';
UPDATE `skill_trees` SET `name` = '居所-勇往直前' WHERE `skill_id` = '607';
UPDATE `skill_trees` SET `name` = '居所-盡忠職守' WHERE `skill_id` = '608';
UPDATE `skill_trees` SET `name` = '居所-兵貴神速' WHERE `skill_id` = '609';
UPDATE `skill_trees` SET `name` = '居所-鞠躬盡瘁' WHERE `skill_id` = '610';
UPDATE `skill_trees` SET `name` = '火小隊' WHERE `skill_id` = '611';
UPDATE `skill_trees` SET `name` = '水小隊' WHERE `skill_id` = '612';
UPDATE `skill_trees` SET `name` = '風小隊' WHERE `skill_id` = '613';
UPDATE `skill_trees` SET `name` = '地小隊' WHERE `skill_id` = '614';
UPDATE `skill_trees` SET `name` = '聖小隊' WHERE `skill_id` = '615';
UPDATE `skill_trees` SET `name` = '暗小隊' WHERE `skill_id` = '616';
UPDATE `skill_trees` SET `name` = '變身 瑪瑙獸' WHERE `skill_id` = '617';
UPDATE `skill_trees` SET `name` = '變身 死亡之刃' WHERE `skill_id` = '618';
UPDATE `skill_trees` SET `name` = '變身 消除' WHERE `skill_id` = '619';
UPDATE `skill_trees` SET `name` = '弩箭筒-B級' WHERE `skill_id` = '620';
UPDATE `skill_trees` SET `name` = '製作特殊弩箭' WHERE `skill_id` = '621';
UPDATE `skill_trees` SET `name` = '極限逃脫' WHERE `skill_id` = '622';
UPDATE `skill_trees` SET `name` = '尋找陷阱' WHERE `skill_id` = '623';
UPDATE `skill_trees` SET `name` = '移除陷阱' WHERE `skill_id` = '624';
UPDATE `skill_trees` SET `name` = '魂魄匯集' WHERE `skill_id` = '625';
UPDATE `skill_trees` SET `name` = '爆擊感識' WHERE `skill_id` = '626';
UPDATE `skill_trees` SET `name` = '靈魂震盪' WHERE `skill_id` = '627';
UPDATE `skill_trees` SET `name` = '曲速' WHERE `skill_id` = '628';
UPDATE `skill_trees` SET `name` = '狡兔魔眼' WHERE `skill_id` = '629';
UPDATE `skill_trees` SET `name` = '狡兔旋風' WHERE `skill_id` = '630';
UPDATE `skill_trees` SET `name` = '副職-初學者 攻擊' WHERE `skill_id` = '631';
UPDATE `skill_trees` SET `name` = '副職-初學者 防禦' WHERE `skill_id` = '632';
UPDATE `skill_trees` SET `name` = '副職-初學者 魔力' WHERE `skill_id` = '633';
UPDATE `skill_trees` SET `name` = '副職-初學者 魔法防禦' WHERE `skill_id` = '634';
UPDATE `skill_trees` SET `name` = '不使用' WHERE `skill_id` = '635';
UPDATE `skill_trees` SET `name` = '不使用' WHERE `skill_id` = '636';
UPDATE `skill_trees` SET `name` = '副職-攻擊專家' WHERE `skill_id` = '637';
UPDATE `skill_trees` SET `name` = '副職-魔力專家' WHERE `skill_id` = '638';
UPDATE `skill_trees` SET `name` = '副職-施法專家' WHERE `skill_id` = '639';
UPDATE `skill_trees` SET `name` = '副職-偵測專家' WHERE `skill_id` = '640';
UPDATE `skill_trees` SET `name` = '騎士能力-生命強化' WHERE `skill_id` = '641';
UPDATE `skill_trees` SET `name` = '法師能力-魔力強化' WHERE `skill_id` = '642';
UPDATE `skill_trees` SET `name` = '召喚士能力-HP/MP強化' WHERE `skill_id` = '643';
UPDATE `skill_trees` SET `name` = '盜賊能力-迴避' WHERE `skill_id` = '644';
UPDATE `skill_trees` SET `name` = '盜賊能力-遠箭術' WHERE `skill_id` = '645';
UPDATE `skill_trees` SET `name` = '巫師能力-魔力回復' WHERE `skill_id` = '646';
UPDATE `skill_trees` SET `name` = '法師能力-魔力恢復' WHERE `skill_id` = '647';
UPDATE `skill_trees` SET `name` = '牧師能力-祈禱' WHERE `skill_id` = '648';
UPDATE `skill_trees` SET `name` = '鬥士能力-特性抵抗' WHERE `skill_id` = '650';
UPDATE `skill_trees` SET `name` = '鬥士能力-速度激發' WHERE `skill_id` = '651';
UPDATE `skill_trees` SET `name` = '騎士能力-防禦' WHERE `skill_id` = '652';
UPDATE `skill_trees` SET `name` = '盜賊能力-致命攻擊機率' WHERE `skill_id` = '653';
UPDATE `skill_trees` SET `name` = '巫師能力-魔力竊取' WHERE `skill_id` = '654';
UPDATE `skill_trees` SET `name` = '法師能力-壁障' WHERE `skill_id` = '655';
UPDATE `skill_trees` SET `name` = '變身 聖恩鬥士' WHERE `skill_id` = '656';
UPDATE `skill_trees` SET `name` = '變身 聖恩騎士' WHERE `skill_id` = '657';
UPDATE `skill_trees` SET `name` = '變身 聖恩盜賊' WHERE `skill_id` = '658';
UPDATE `skill_trees` SET `name` = '變身 聖恩巫師' WHERE `skill_id` = '659';
UPDATE `skill_trees` SET `name` = '變身 聖恩召喚士' WHERE `skill_id` = '660';
UPDATE `skill_trees` SET `name` = '變身 聖恩牧師' WHERE `skill_id` = '661';
UPDATE `skill_trees` SET `name` = '變身 聖恩法師' WHERE `skill_id` = '662';
UPDATE `skill_trees` SET `name` = '變身 札肯' WHERE `skill_id` = '663';
UPDATE `skill_trees` SET `name` = '變身 亞納' WHERE `skill_id` = '664';
UPDATE `skill_trees` SET `name` = '變身 貝諾姆' WHERE `skill_id` = '665';
UPDATE `skill_trees` SET `name` = '變身 高登' WHERE `skill_id` = '666';
UPDATE `skill_trees` SET `name` = '變身 勞庫' WHERE `skill_id` = '667';
UPDATE `skill_trees` SET `name` = '變身 基亞齊' WHERE `skill_id` = '668';
UPDATE `skill_trees` SET `name` = '變身 惡魔公爵' WHERE `skill_id` = '669';
UPDATE `skill_trees` SET `name` = '變身 異教徒' WHERE `skill_id` = '670';
UPDATE `skill_trees` SET `name` = '變身 貝里大師' WHERE `skill_id` = '671';
UPDATE `skill_trees` SET `name` = '變身 劍齒虎' WHERE `skill_id` = '672';
UPDATE `skill_trees` SET `name` = '變身 奧耶豺狼' WHERE `skill_id` = '673';
UPDATE `skill_trees` SET `name` = '變身 人偶刀手' WHERE `skill_id` = '674';
UPDATE `skill_trees` SET `name` = '聖恩鬥士 十字斬' WHERE `skill_id` = '675';
UPDATE `skill_trees` SET `name` = '聖恩鬥士 波動衝擊' WHERE `skill_id` = '676';
UPDATE `skill_trees` SET `name` = '聖恩鬥士 地之貫殺' WHERE `skill_id` = '677';
UPDATE `skill_trees` SET `name` = '聖恩鬥士 戰之狂嚎' WHERE `skill_id` = '678';
UPDATE `skill_trees` SET `name` = '鬥士 獻祭' WHERE `skill_id` = '679';
UPDATE `skill_trees` SET `name` = '聖恩騎士 挑撥' WHERE `skill_id` = '680';
UPDATE `skill_trees` SET `name` = '聖恩騎士 強力挑撥' WHERE `skill_id` = '681';
UPDATE `skill_trees` SET `name` = '聖恩騎士 昏迷之擊' WHERE `skill_id` = '682';
UPDATE `skill_trees` SET `name` = '聖恩騎士 怒雷風暴' WHERE `skill_id` = '683';
UPDATE `skill_trees` SET `name` = '聖恩騎士 極限防禦' WHERE `skill_id` = '684';
UPDATE `skill_trees` SET `name` = '騎士 獻祭' WHERE `skill_id` = '685';
UPDATE `skill_trees` SET `name` = '聖恩盜賊 衝擊箭' WHERE `skill_id` = '686';
UPDATE `skill_trees` SET `name` = '聖恩盜賊 連環箭' WHERE `skill_id` = '687';
UPDATE `skill_trees` SET `name` = '聖恩盜賊 出血攻擊' WHERE `skill_id` = '688';
UPDATE `skill_trees` SET `name` = '聖恩盜賊 致命之息' WHERE `skill_id` = '689';
UPDATE `skill_trees` SET `name` = '聖恩盜賊 敏捷術' WHERE `skill_id` = '690';
UPDATE `skill_trees` SET `name` = '盜賊 獻祭' WHERE `skill_id` = '691';
UPDATE `skill_trees` SET `name` = '聖恩巫師 神聖火焰' WHERE `skill_id` = '692';
UPDATE `skill_trees` SET `name` = '聖恩巫師 神聖之擊' WHERE `skill_id` = '693';
UPDATE `skill_trees` SET `name` = '聖恩巫師 神聖之幕' WHERE `skill_id` = '694';
UPDATE `skill_trees` SET `name` = '聖恩巫師 神聖之雲' WHERE `skill_id` = '695';
UPDATE `skill_trees` SET `name` = '聖恩巫師 聖之陷落' WHERE `skill_id` = '696';
UPDATE `skill_trees` SET `name` = '巫師 獻祭' WHERE `skill_id` = '697';
UPDATE `skill_trees` SET `name` = '聖恩牧師 極大治癒術' WHERE `skill_id` = '698';
UPDATE `skill_trees` SET `name` = '聖恩牧師 急救術' WHERE `skill_id` = '699';
UPDATE `skill_trees` SET `name` = '聖恩牧師 集體治癒術' WHERE `skill_id` = '700';
UPDATE `skill_trees` SET `name` = '聖恩牧師 返生術' WHERE `skill_id` = '701';
UPDATE `skill_trees` SET `name` = '聖恩牧師 淨罪' WHERE `skill_id` = '702';
UPDATE `skill_trees` SET `name` = '牧師 獻祭' WHERE `skill_id` = '703';
UPDATE `skill_trees` SET `name` = '聖恩法師 水靈' WHERE `skill_id` = '704';
UPDATE `skill_trees` SET `name` = '聖恩法師 火靈' WHERE `skill_id` = '705';
UPDATE `skill_trees` SET `name` = '聖恩法師 風靈' WHERE `skill_id` = '706';
UPDATE `skill_trees` SET `name` = '聖恩法師 英雄之靈' WHERE `skill_id` = '707';
UPDATE `skill_trees` SET `name` = '聖恩法師 約束結界' WHERE `skill_id` = '708';
UPDATE `skill_trees` SET `name` = '法師 獻祭' WHERE `skill_id` = '709';
UPDATE `skill_trees` SET `name` = '聖恩召喚士 召喚聖恩獸' WHERE `skill_id` = '710';
UPDATE `skill_trees` SET `name` = '聖恩召喚士 痛苦轉移' WHERE `skill_id` = '711';
UPDATE `skill_trees` SET `name` = '聖恩召喚士 終極使魔' WHERE `skill_id` = '712';
UPDATE `skill_trees` SET `name` = '聖恩召喚士 使魔生命回復' WHERE `skill_id` = '713';
UPDATE `skill_trees` SET `name` = '召喚士 獻祭' WHERE `skill_id` = '714';
UPDATE `skill_trees` SET `name` = '札肯 能量吸收' WHERE `skill_id` = '715';
UPDATE `skill_trees` SET `name` = '札肯 束縛' WHERE `skill_id` = '716';
UPDATE `skill_trees` SET `name` = '札肯 全力攻擊' WHERE `skill_id` = '717';
UPDATE `skill_trees` SET `name` = '札肯 飛舞之劍' WHERE `skill_id` = '718';
UPDATE `skill_trees` SET `name` = '札肯 吸血怒擊' WHERE `skill_id` = '719';
UPDATE `skill_trees` SET `name` = '亞納 聖光爆裂' WHERE `skill_id` = '720';
UPDATE `skill_trees` SET `name` = '亞納 能量攻擊' WHERE `skill_id` = '721';
UPDATE `skill_trees` SET `name` = '亞納 神聖光束' WHERE `skill_id` = '722';
UPDATE `skill_trees` SET `name` = '亞納 日光術' WHERE `skill_id` = '723';
UPDATE `skill_trees` SET `name` = '亞納 淨罪' WHERE `skill_id` = '724';
UPDATE `skill_trees` SET `name` = '貝諾姆 能量破擊' WHERE `skill_id` = '725';
UPDATE `skill_trees` SET `name` = '貝諾姆 波動風暴' WHERE `skill_id` = '726';
UPDATE `skill_trees` SET `name` = '貝諾姆 幻滅' WHERE `skill_id` = '727';
UPDATE `skill_trees` SET `name` = '高登 獸擊' WHERE `skill_id` = '728';
UPDATE `skill_trees` SET `name` = '高登 劍刺' WHERE `skill_id` = '729';
UPDATE `skill_trees` SET `name` = '高登 擠壓' WHERE `skill_id` = '730';
UPDATE `skill_trees` SET `name` = '勞庫 黑暗爆裂' WHERE `skill_id` = '731';
UPDATE `skill_trees` SET `name` = '勞庫 昏迷之擊' WHERE `skill_id` = '732';
UPDATE `skill_trees` SET `name` = '基亞齊 雙刃殺' WHERE `skill_id` = '733';
UPDATE `skill_trees` SET `name` = '基亞齊 大氣之刃' WHERE `skill_id` = '734';
UPDATE `skill_trees` SET `name` = '惡魔 揮舞兵器' WHERE `skill_id` = '735';
UPDATE `skill_trees` SET `name` = '惡魔 種子' WHERE `skill_id` = '736';
UPDATE `skill_trees` SET `name` = '惡魔 極限防禦' WHERE `skill_id` = '737';
UPDATE `skill_trees` SET `name` = '異教徒 治療術' WHERE `skill_id` = '738';
UPDATE `skill_trees` SET `name` = '異教徒 急救術' WHERE `skill_id` = '739';
UPDATE `skill_trees` SET `name` = '異教徒 返生術' WHERE `skill_id` = '740';
UPDATE `skill_trees` SET `name` = '異教徒 治療副作用' WHERE `skill_id` = '741';
UPDATE `skill_trees` SET `name` = '貝里大師 爆裂火焰' WHERE `skill_id` = '742';
UPDATE `skill_trees` SET `name` = '貝里大師 黑暗爆裂' WHERE `skill_id` = '743';
UPDATE `skill_trees` SET `name` = '貝里大師 黑暗閃焰' WHERE `skill_id` = '744';
UPDATE `skill_trees` SET `name` = '貝里大師 黑暗治療' WHERE `skill_id` = '745';
UPDATE `skill_trees` SET `name` = '劍齒虎 撕咬' WHERE `skill_id` = '746';
UPDATE `skill_trees` SET `name` = '劍齒虎 恐懼' WHERE `skill_id` = '747';
UPDATE `skill_trees` SET `name` = '劍齒虎 疾風衝刺' WHERE `skill_id` = '748';
UPDATE `skill_trees` SET `name` = '奧耶豺狼 昏迷之擊' WHERE `skill_id` = '749';
UPDATE `skill_trees` SET `name` = '奧耶豺狼 極限防禦' WHERE `skill_id` = '750';
UPDATE `skill_trees` SET `name` = '奧耶豺狼 揮動武器' WHERE `skill_id` = '751';
UPDATE `skill_trees` SET `name` = '人偶刀手 要害刺擊' WHERE `skill_id` = '752';
UPDATE `skill_trees` SET `name` = '人偶刀手 飛刀' WHERE `skill_id` = '753';
UPDATE `skill_trees` SET `name` = '人偶刀手 洞察之眼' WHERE `skill_id` = '754';
UPDATE `skill_trees` SET `name` = '古文保護' WHERE `skill_id` = '755';
UPDATE `skill_trees` SET `name` = '元素保護' WHERE `skill_id` = '756';
UPDATE `skill_trees` SET `name` = '團結保護' WHERE `skill_id` = '757';
UPDATE `skill_trees` SET `name` = '戰士的意志' WHERE `skill_id` = '758';
UPDATE `skill_trees` SET `name` = '弓手的意志' WHERE `skill_id` = '759';
UPDATE `skill_trees` SET `name` = '抗魔裝甲' WHERE `skill_id` = '760';
UPDATE `skill_trees` SET `name` = '復仇種子' WHERE `skill_id` = '761';
UPDATE `skill_trees` SET `name` = '瘋狂巨鎚' WHERE `skill_id` = '762';
UPDATE `skill_trees` SET `name` = '地獄狂嘯' WHERE `skill_id` = '763';
UPDATE `skill_trees` SET `name` = '風暴之歌' WHERE `skill_id` = '764';
UPDATE `skill_trees` SET `name` = '刀刃風暴之舞' WHERE `skill_id` = '765';
UPDATE `skill_trees` SET `name` = '第六感' WHERE `skill_id` = '766';
UPDATE `skill_trees` SET `name` = '弱點揭露' WHERE `skill_id` = '767';
UPDATE `skill_trees` SET `name` = '狂熱鬥志' WHERE `skill_id` = '768';
UPDATE `skill_trees` SET `name` = '御風' WHERE `skill_id` = '769';
UPDATE `skill_trees` SET `name` = '鬼行' WHERE `skill_id` = '770';
UPDATE `skill_trees` SET `name` = '火焰之鷹' WHERE `skill_id` = '771';
UPDATE `skill_trees` SET `name` = '箭雨' WHERE `skill_id` = '772';
UPDATE `skill_trees` SET `name` = '鬼刺' WHERE `skill_id` = '773';
UPDATE `skill_trees` SET `name` = '恐懼佈滿' WHERE `skill_id` = '774';
UPDATE `skill_trees` SET `name` = '武器封鎖' WHERE `skill_id` = '775';
UPDATE `skill_trees` SET `name` = '毀滅之力' WHERE `skill_id` = '776';
UPDATE `skill_trees` SET `name` = '壞滅衝擊' WHERE `skill_id` = '777';
UPDATE `skill_trees` SET `name` = '高崙裝甲' WHERE `skill_id` = '778';
UPDATE `skill_trees` SET `name` = '召喚聰慧晶體' WHERE `skill_id` = '779';
UPDATE `skill_trees` SET `name` = '召喚聰慧晶體' WHERE `skill_id` = '780';
UPDATE `skill_trees` SET `name` = '召喚聰慧晶體' WHERE `skill_id` = '781';
UPDATE `skill_trees` SET `name` = '召喚聰慧晶體' WHERE `skill_id` = '782';
UPDATE `skill_trees` SET `name` = '召喚聰慧晶體' WHERE `skill_id` = '783';
UPDATE `skill_trees` SET `name` = '鳳凰之魂' WHERE `skill_id` = '784';
UPDATE `skill_trees` SET `name` = '火焰靈能' WHERE `skill_id` = '785';
UPDATE `skill_trees` SET `name` = '伊娃意志' WHERE `skill_id` = '786';
UPDATE `skill_trees` SET `name` = '伊娃之觸' WHERE `skill_id` = '787';
UPDATE `skill_trees` SET `name` = '席琳之痛' WHERE `skill_id` = '788';
UPDATE `skill_trees` SET `name` = '席琳之觸' WHERE `skill_id` = '789';
UPDATE `skill_trees` SET `name` = '野性射擊' WHERE `skill_id` = '790';
UPDATE `skill_trees` SET `name` = '強雷震盪' WHERE `skill_id` = '791';
UPDATE `skill_trees` SET `name` = '背叛印記' WHERE `skill_id` = '792';
UPDATE `skill_trees` SET `name` = '疾襲衝擊' WHERE `skill_id` = '793';
UPDATE `skill_trees` SET `name` = '集體卸除武器' WHERE `skill_id` = '794';
UPDATE `skill_trees` SET `name` = '聖恩騎士 揮擊' WHERE `skill_id` = '795';
UPDATE `skill_trees` SET `name` = '聖恩騎士 爆烈攻擊' WHERE `skill_id` = '796';
UPDATE `skill_trees` SET `name` = '聖恩盜賊穿刺攻擊' WHERE `skill_id` = '797';
UPDATE `skill_trees` SET `name` = '聖恩鬥士 正面攻擊' WHERE `skill_id` = '798';
UPDATE `skill_trees` SET `name` = '副職-物理防禦專家' WHERE `skill_id` = '799';
UPDATE `skill_trees` SET `name` = '副職-魔法防禦專家' WHERE `skill_id` = '800';
UPDATE `skill_trees` SET `name` = '鬥士能力-CP強化' WHERE `skill_id` = '801';
UPDATE `skill_trees` SET `name` = '巫師能力-抗魔術' WHERE `skill_id` = '802';
UPDATE `skill_trees` SET `name` = '牧師能力-神聖加護' WHERE `skill_id` = '803';
UPDATE `skill_trees` SET `name` = '騎士能力-致命攻擊抵抗' WHERE `skill_id` = '804';
UPDATE `skill_trees` SET `name` = 'not used' WHERE `skill_id` = '805';
UPDATE `skill_trees` SET `name` = '魔法妨礙' WHERE `skill_id` = '806';
UPDATE `skill_trees` SET `name` = 'Overhit' WHERE `skill_id` = '807';
UPDATE `skill_trees` SET `name` = '高崙之擊' WHERE `skill_id` = '808';
UPDATE `skill_trees` SET `name` = '高崙旋風揮擊' WHERE `skill_id` = '809';
UPDATE `skill_trees` SET `name` = '先鋒' WHERE `skill_id` = '810';
UPDATE `skill_trees` SET `name` = '先鋒' WHERE `skill_id` = '811';
UPDATE `skill_trees` SET `name` = '先鋒' WHERE `skill_id` = '812';
UPDATE `skill_trees` SET `name` = '先鋒' WHERE `skill_id` = '813';
UPDATE `skill_trees` SET `name` = '全力揮擊' WHERE `skill_id` = '814';
UPDATE `skill_trees` SET `name` = '刀刃颶風' WHERE `skill_id` = '815';
UPDATE `skill_trees` SET `name` = '強力斷斬' WHERE `skill_id` = '816';
UPDATE `skill_trees` SET `name` = '連環擊' WHERE `skill_id` = '817';
UPDATE `skill_trees` SET `name` = '迴避反擊' WHERE `skill_id` = '818';
UPDATE `skill_trees` SET `name` = '迴避契機' WHERE `skill_id` = '819';
UPDATE `skill_trees` SET `name` = '迴避激發' WHERE `skill_id` = '820';
UPDATE `skill_trees` SET `name` = '影步' WHERE `skill_id` = '821';
UPDATE `skill_trees` SET `name` = '高崙維修' WHERE `skill_id` = '822';
UPDATE `skill_trees` SET `name` = '強大之力' WHERE `skill_id` = '823';
UPDATE `skill_trees` SET `name` = '防禦武裝' WHERE `skill_id` = '824';
UPDATE `skill_trees` SET `name` = '尖銳之刃' WHERE `skill_id` = '825';
UPDATE `skill_trees` SET `name` = '釘鎚穿刺' WHERE `skill_id` = '826';
UPDATE `skill_trees` SET `name` = '弓弦強化' WHERE `skill_id` = '827';
UPDATE `skill_trees` SET `name` = '表層硬化' WHERE `skill_id` = '828';
UPDATE `skill_trees` SET `name` = '表革硬化' WHERE `skill_id` = '829';
UPDATE `skill_trees` SET `name` = '紋刻' WHERE `skill_id` = '830';
UPDATE `skill_trees` SET `name` = '召喚商業高崙' WHERE `skill_id` = '831';
UPDATE `skill_trees` SET `name` = '速效恢復' WHERE `skill_id` = '832';
UPDATE `skill_trees` SET `name` = '重建之體' WHERE `skill_id` = '833';
UPDATE `skill_trees` SET `name` = '血之契約' WHERE `skill_id` = '834';
UPDATE `skill_trees` SET `name` = '植入末日種子' WHERE `skill_id` = '835';
UPDATE `skill_trees` SET `name` = '忘卻陷阱' WHERE `skill_id` = '836';
UPDATE `skill_trees` SET `name` = '止痛術' WHERE `skill_id` = '837';
UPDATE `skill_trees` SET `name` = '態度轉化' WHERE `skill_id` = '838';
UPDATE `skill_trees` SET `name` = '降下' WHERE `skill_id` = '839';
UPDATE `skill_trees` SET `name` = '靈魂之泣' WHERE `skill_id` = '1001';
UPDATE `skill_trees` SET `name` = '靈火頌歌' WHERE `skill_id` = '1002';
UPDATE `skill_trees` SET `name` = '帕格立歐力量' WHERE `skill_id` = '1003';
UPDATE `skill_trees` SET `name` = '帕格立歐智慧' WHERE `skill_id` = '1004';
UPDATE `skill_trees` SET `name` = '帕格立歐祝福' WHERE `skill_id` = '1005';
UPDATE `skill_trees` SET `name` = '聖火頌歌' WHERE `skill_id` = '1006';
UPDATE `skill_trees` SET `name` = '狂戰頌歌' WHERE `skill_id` = '1007';
UPDATE `skill_trees` SET `name` = '帕格立歐榮光' WHERE `skill_id` = '1008';
UPDATE `skill_trees` SET `name` = '鐵壁頌歌' WHERE `skill_id` = '1009';
UPDATE `skill_trees` SET `name` = '聖靈之盾' WHERE `skill_id` = '1010';
UPDATE `skill_trees` SET `name` = '治癒術' WHERE `skill_id` = '1011';
UPDATE `skill_trees` SET `name` = '療毒術' WHERE `skill_id` = '1012';
UPDATE `skill_trees` SET `name` = '回復術' WHERE `skill_id` = '1013';
UPDATE `skill_trees` SET `name` = '急救術' WHERE `skill_id` = '1015';
UPDATE `skill_trees` SET `name` = '返生術' WHERE `skill_id` = '1016';
UPDATE `skill_trees` SET `name` = '淨化' WHERE `skill_id` = '1018';
UPDATE `skill_trees` SET `name` = '活力激發' WHERE `skill_id` = '1020';
UPDATE `skill_trees` SET `name` = '集體治癒術' WHERE `skill_id` = '1027';
UPDATE `skill_trees` SET `name` = '天之箭' WHERE `skill_id` = '1028';
UPDATE `skill_trees` SET `name` = '不死生物破壞' WHERE `skill_id` = '1031';
UPDATE `skill_trees` SET `name` = '充沛活力' WHERE `skill_id` = '1032';
UPDATE `skill_trees` SET `name` = '毒性抵抗' WHERE `skill_id` = '1033';
UPDATE `skill_trees` SET `name` = '安靈曲' WHERE `skill_id` = '1034';
UPDATE `skill_trees` SET `name` = '心靈防護' WHERE `skill_id` = '1035';
UPDATE `skill_trees` SET `name` = '魔法屏障' WHERE `skill_id` = '1036';
UPDATE `skill_trees` SET `name` = '保護盾' WHERE `skill_id` = '1040';
UPDATE `skill_trees` SET `name` = '不死生物束縛' WHERE `skill_id` = '1042';
UPDATE `skill_trees` SET `name` = '神聖武器' WHERE `skill_id` = '1043';
UPDATE `skill_trees` SET `name` = '強癒術' WHERE `skill_id` = '1044';
UPDATE `skill_trees` SET `name` = '神佑之體' WHERE `skill_id` = '1045';
UPDATE `skill_trees` SET `name` = '魔力再生' WHERE `skill_id` = '1047';
UPDATE `skill_trees` SET `name` = '神佑之魂' WHERE `skill_id` = '1048';
UPDATE `skill_trees` SET `name` = '鎮魂曲' WHERE `skill_id` = '1049';
UPDATE `skill_trees` SET `name` = '回歸術' WHERE `skill_id` = '1050';
UPDATE `skill_trees` SET `name` = '魔法消除' WHERE `skill_id` = '1056';
UPDATE `skill_trees` SET `name` = '魔力催化' WHERE `skill_id` = '1059';
UPDATE `skill_trees` SET `name` = '狂戰士魂' WHERE `skill_id` = '1062';
UPDATE `skill_trees` SET `name` = '沉默術' WHERE `skill_id` = '1064';
UPDATE `skill_trees` SET `name` = '力量強化' WHERE `skill_id` = '1068';
UPDATE `skill_trees` SET `name` = '催眠術' WHERE `skill_id` = '1069';
UPDATE `skill_trees` SET `name` = '水之陷落' WHERE `skill_id` = '1071';
UPDATE `skill_trees` SET `name` = '沉睡之雲' WHERE `skill_id` = '1072';
UPDATE `skill_trees` SET `name` = '伊娃之吻' WHERE `skill_id` = '1073';
UPDATE `skill_trees` SET `name` = '風之陷落' WHERE `skill_id` = '1074';
UPDATE `skill_trees` SET `name` = '氣息平靜' WHERE `skill_id` = '1075';
UPDATE `skill_trees` SET `name` = '弱點偵測' WHERE `skill_id` = '1077';
UPDATE `skill_trees` SET `name` = '精神專注' WHERE `skill_id` = '1078';
UPDATE `skill_trees` SET `name` = '火之陷落' WHERE `skill_id` = '1083';
UPDATE `skill_trees` SET `name` = '靈活思緒' WHERE `skill_id` = '1085';
UPDATE `skill_trees` SET `name` = '速度激發' WHERE `skill_id` = '1086';
UPDATE `skill_trees` SET `name` = '敏捷術' WHERE `skill_id` = '1087';
UPDATE `skill_trees` SET `name` = '生命吸收' WHERE `skill_id` = '1090';
UPDATE `skill_trees` SET `name` = '心之恐懼' WHERE `skill_id` = '1092';
UPDATE `skill_trees` SET `name` = '痛苦之刺' WHERE `skill_id` = '1095';
UPDATE `skill_trees` SET `name` = '混亂封印' WHERE `skill_id` = '1096';
UPDATE `skill_trees` SET `name` = '睡夢之靈' WHERE `skill_id` = '1097';
UPDATE `skill_trees` SET `name` = '緩速封印' WHERE `skill_id` = '1099';
UPDATE `skill_trees` SET `name` = '戰慄之火' WHERE `skill_id` = '1100';
UPDATE `skill_trees` SET `name` = '火焰震憾' WHERE `skill_id` = '1101';
UPDATE `skill_trees` SET `name` = '靈氣沉淪' WHERE `skill_id` = '1102';
UPDATE `skill_trees` SET `name` = '寒冬封印' WHERE `skill_id` = '1104';
UPDATE `skill_trees` SET `name` = '心靈喪失' WHERE `skill_id` = '1105';
UPDATE `skill_trees` SET `name` = '寒霜之焰' WHERE `skill_id` = '1107';
UPDATE `skill_trees` SET `name` = '火焰封印' WHERE `skill_id` = '1108';
UPDATE `skill_trees` SET `name` = '召喚戰鬥貓' WHERE `skill_id` = '1111';
UPDATE `skill_trees` SET `name` = '使魔魔力回復' WHERE `skill_id` = '1126';
UPDATE `skill_trees` SET `name` = '使魔生命回復' WHERE `skill_id` = '1127';
UPDATE `skill_trees` SET `name` = '召喚闇魔' WHERE `skill_id` = '1128';
UPDATE `skill_trees` SET `name` = '召喚起死回生者' WHERE `skill_id` = '1129';
UPDATE `skill_trees` SET `name` = '使魔魔法盾' WHERE `skill_id` = '1139';
UPDATE `skill_trees` SET `name` = '使魔能量盾' WHERE `skill_id` = '1140';
UPDATE `skill_trees` SET `name` = '使魔速度激發' WHERE `skill_id` = '1141';
UPDATE `skill_trees` SET `name` = '快速使魔' WHERE `skill_id` = '1144';
UPDATE `skill_trees` SET `name` = '睿智使魔' WHERE `skill_id` = '1145';
UPDATE `skill_trees` SET `name` = '強力使魔' WHERE `skill_id` = '1146';
UPDATE `skill_trees` SET `name` = '吸血鬼之吻' WHERE `skill_id` = '1147';
UPDATE `skill_trees` SET `name` = '死亡之刺' WHERE `skill_id` = '1148';
UPDATE `skill_trees` SET `name` = '死體能量吸收' WHERE `skill_id` = '1151';
UPDATE `skill_trees` SET `name` = '召喚腐屍' WHERE `skill_id` = '1154';
UPDATE `skill_trees` SET `name` = '屍體爆裂' WHERE `skill_id` = '1155';
UPDATE `skill_trees` SET `name` = '遺忘術' WHERE `skill_id` = '1156';
UPDATE `skill_trees` SET `name` = '心靈轉換' WHERE `skill_id` = '1157';
UPDATE `skill_trees` SET `name` = '死之糾結' WHERE `skill_id` = '1159';
UPDATE `skill_trees` SET `name` = '緩速術' WHERE `skill_id` = '1160';
UPDATE `skill_trees` SET `name` = '迷魅之咒' WHERE `skill_id` = '1163';
UPDATE `skill_trees` SET `name` = '弱化術' WHERE `skill_id` = '1164';
UPDATE `skill_trees` SET `name` = '劇毒之雲' WHERE `skill_id` = '1167';
UPDATE `skill_trees` SET `name` = '毒咒術' WHERE `skill_id` = '1168';
UPDATE `skill_trees` SET `name` = '恐懼之咒' WHERE `skill_id` = '1169';
UPDATE `skill_trees` SET `name` = '定身術' WHERE `skill_id` = '1170';
UPDATE `skill_trees` SET `name` = '赤燄之輪' WHERE `skill_id` = '1171';
UPDATE `skill_trees` SET `name` = '精神燃燒' WHERE `skill_id` = '1172';
UPDATE `skill_trees` SET `name` = '冰凍之牆' WHERE `skill_id` = '1174';
UPDATE `skill_trees` SET `name` = '水漩渦' WHERE `skill_id` = '1175';
UPDATE `skill_trees` SET `name` = '颶風術' WHERE `skill_id` = '1176';
UPDATE `skill_trees` SET `name` = '狂風之擊' WHERE `skill_id` = '1177';
UPDATE `skill_trees` SET `name` = '風漩術' WHERE `skill_id` = '1178';
UPDATE `skill_trees` SET `name` = '火焰狂襲' WHERE `skill_id` = '1181';
UPDATE `skill_trees` SET `name` = '水之防護' WHERE `skill_id` = '1182';
UPDATE `skill_trees` SET `name` = '冰之鎖' WHERE `skill_id` = '1183';
UPDATE `skill_trees` SET `name` = '冰箭術' WHERE `skill_id` = '1184';
UPDATE `skill_trees` SET `name` = '風之防護' WHERE `skill_id` = '1189';
UPDATE `skill_trees` SET `name` = '火之防護' WHERE `skill_id` = '1191';
UPDATE `skill_trees` SET `name` = '樹精之足' WHERE `skill_id` = '1201';
UPDATE `skill_trees` SET `name` = '風之疾走' WHERE `skill_id` = '1204';
UPDATE `skill_trees` SET `name` = '風之鎖' WHERE `skill_id` = '1206';
UPDATE `skill_trees` SET `name` = '約束封印' WHERE `skill_id` = '1208';
UPDATE `skill_trees` SET `name` = '劇毒封印' WHERE `skill_id` = '1209';
UPDATE `skill_trees` SET `name` = '黑暗封印' WHERE `skill_id` = '1210';
UPDATE `skill_trees` SET `name` = '幻惑封印' WHERE `skill_id` = '1213';
UPDATE `skill_trees` SET `name` = '自我治癒' WHERE `skill_id` = '1216';
UPDATE `skill_trees` SET `name` = '終極治癒術' WHERE `skill_id` = '1217';
UPDATE `skill_trees` SET `name` = '終極急救術' WHERE `skill_id` = '1218';
UPDATE `skill_trees` SET `name` = '終極集體治癒術' WHERE `skill_id` = '1219';
UPDATE `skill_trees` SET `name` = '赤焰燃燒' WHERE `skill_id` = '1220';
UPDATE `skill_trees` SET `name` = '混亂之咒' WHERE `skill_id` = '1222';
UPDATE `skill_trees` SET `name` = '土之陷落' WHERE `skill_id` = '1223';
UPDATE `skill_trees` SET `name` = '毒之陷落' WHERE `skill_id` = '1224';
UPDATE `skill_trees` SET `name` = '召喚魔法貓' WHERE `skill_id` = '1225';
UPDATE `skill_trees` SET `name` = '召喚戰鬥獨角獸' WHERE `skill_id` = '1226';
UPDATE `skill_trees` SET `name` = '召喚夢幻獨角獸' WHERE `skill_id` = '1227';
UPDATE `skill_trees` SET `name` = '召喚影魔' WHERE `skill_id` = '1228';
UPDATE `skill_trees` SET `name` = '生命禮讚' WHERE `skill_id` = '1229';
UPDATE `skill_trees` SET `name` = '風之爆裂' WHERE `skill_id` = '1230';
UPDATE `skill_trees` SET `name` = '精神爆發' WHERE `skill_id` = '1231';
UPDATE `skill_trees` SET `name` = '燃燒之體' WHERE `skill_id` = '1232';
UPDATE `skill_trees` SET `name` = '腐蝕術' WHERE `skill_id` = '1233';
UPDATE `skill_trees` SET `name` = '吸血鬼之爪' WHERE `skill_id` = '1234';
UPDATE `skill_trees` SET `name` = '水之爆裂' WHERE `skill_id` = '1235';
UPDATE `skill_trees` SET `name` = '寒霜之箭' WHERE `skill_id` = '1236';
UPDATE `skill_trees` SET `name` = '冰之匕' WHERE `skill_id` = '1237';
UPDATE `skill_trees` SET `name` = '凍結之體' WHERE `skill_id` = '1238';
UPDATE `skill_trees` SET `name` = '暴風雨' WHERE `skill_id` = '1239';
UPDATE `skill_trees` SET `name` = '導引' WHERE `skill_id` = '1240';
UPDATE `skill_trees` SET `name` = '死之呢喃' WHERE `skill_id` = '1242';
UPDATE `skill_trees` SET `name` = '祝福之盾' WHERE `skill_id` = '1243';
UPDATE `skill_trees` SET `name` = '極冰之燄' WHERE `skill_id` = '1244';
UPDATE `skill_trees` SET `name` = '竊取精髓' WHERE `skill_id` = '1245';
UPDATE `skill_trees` SET `name` = '沉默封印' WHERE `skill_id` = '1246';
UPDATE `skill_trees` SET `name` = '生命封印' WHERE `skill_id` = '1247';
UPDATE `skill_trees` SET `name` = '遲鈍封印' WHERE `skill_id` = '1248';
UPDATE `skill_trees` SET `name` = '帕格立歐之眼' WHERE `skill_id` = '1249';
UPDATE `skill_trees` SET `name` = '帕格立歐之盾' WHERE `skill_id` = '1250';
UPDATE `skill_trees` SET `name` = '狂暴頌歌' WHERE `skill_id` = '1251';
UPDATE `skill_trees` SET `name` = '迴避頌歌' WHERE `skill_id` = '1252';
UPDATE `skill_trees` SET `name` = '盛怒頌歌' WHERE `skill_id` = '1253';
UPDATE `skill_trees` SET `name` = '團體返生術' WHERE `skill_id` = '1254';
UPDATE `skill_trees` SET `name` = '隊伍回歸術' WHERE `skill_id` = '1255';
UPDATE `skill_trees` SET `name` = '帕格立歐之心' WHERE `skill_id` = '1256';
UPDATE `skill_trees` SET `name` = '減輕負重' WHERE `skill_id` = '1257';
UPDATE `skill_trees` SET `name` = '生命治癒' WHERE `skill_id` = '1258';
UPDATE `skill_trees` SET `name` = '抵抗休克' WHERE `skill_id` = '1259';
UPDATE `skill_trees` SET `name` = '帕格立歐迅捷' WHERE `skill_id` = '1260';
UPDATE `skill_trees` SET `name` = '帕格立歐憤怒' WHERE `skill_id` = '1261';
UPDATE `skill_trees` SET `name` = '痛苦轉移' WHERE `skill_id` = '1262';
UPDATE `skill_trees` SET `name` = '暗影詛咒' WHERE `skill_id` = '1263';
UPDATE `skill_trees` SET `name` = '太陽閃光' WHERE `skill_id` = '1264';
UPDATE `skill_trees` SET `name` = '太陽火焰' WHERE `skill_id` = '1265';
UPDATE `skill_trees` SET `name` = '暗影閃光' WHERE `skill_id` = '1266';
UPDATE `skill_trees` SET `name` = '暗影火焰' WHERE `skill_id` = '1267';
UPDATE `skill_trees` SET `name` = '吸血怒擊' WHERE `skill_id` = '1268';
UPDATE `skill_trees` SET `name` = '詛咒之疾' WHERE `skill_id` = '1269';
UPDATE `skill_trees` SET `name` = '祝禱' WHERE `skill_id` = '1271';
UPDATE `skill_trees` SET `name` = '恐懼訊息' WHERE `skill_id` = '1272';
UPDATE `skill_trees` SET `name` = '伊娃的小夜曲' WHERE `skill_id` = '1273';
UPDATE `skill_trees` SET `name` = '能量彈' WHERE `skill_id` = '1274';
UPDATE `skill_trees` SET `name` = '靈氣彈' WHERE `skill_id` = '1275';
UPDATE `skill_trees` SET `name` = '召喚銀色貓' WHERE `skill_id` = '1276';
UPDATE `skill_trees` SET `name` = '召喚藍眼獨角獸' WHERE `skill_id` = '1277';
UPDATE `skill_trees` SET `name` = '召喚失魂者' WHERE `skill_id` = '1278';
UPDATE `skill_trees` SET `name` = '召喚麻痺晶體' WHERE `skill_id` = '1279';
UPDATE `skill_trees` SET `name` = '召喚水液晶體' WHERE `skill_id` = '1280';
UPDATE `skill_trees` SET `name` = '召喚火光晶體' WHERE `skill_id` = '1281';
UPDATE `skill_trees` SET `name` = '帕格立歐神速' WHERE `skill_id` = '1282';
UPDATE `skill_trees` SET `name` = '靈魂守護' WHERE `skill_id` = '1283';
UPDATE `skill_trees` SET `name` = '復仇頌歌' WHERE `skill_id` = '1284';
UPDATE `skill_trees` SET `name` = '火的種子' WHERE `skill_id` = '1285';
UPDATE `skill_trees` SET `name` = '水的種子' WHERE `skill_id` = '1286';
UPDATE `skill_trees` SET `name` = '風的種子' WHERE `skill_id` = '1287';
UPDATE `skill_trees` SET `name` = '光暈交響曲' WHERE `skill_id` = '1288';
UPDATE `skill_trees` SET `name` = '地獄火' WHERE `skill_id` = '1289';
UPDATE `skill_trees` SET `name` = '暴風雪' WHERE `skill_id` = '1290';
UPDATE `skill_trees` SET `name` = '惡魔之風' WHERE `skill_id` = '1291';
UPDATE `skill_trees` SET `name` = '元素之擊' WHERE `skill_id` = '1292';
UPDATE `skill_trees` SET `name` = '元素交響曲' WHERE `skill_id` = '1293';
UPDATE `skill_trees` SET `name` = '元素風暴' WHERE `skill_id` = '1294';
UPDATE `skill_trees` SET `name` = '怒濤奔浪' WHERE `skill_id` = '1295';
UPDATE `skill_trees` SET `name` = '火山爆發' WHERE `skill_id` = '1296';
UPDATE `skill_trees` SET `name` = '沉靜之心' WHERE `skill_id` = '1297';
UPDATE `skill_trees` SET `name` = '團體緩速術' WHERE `skill_id` = '1298';
UPDATE `skill_trees` SET `name` = '使魔極限防禦' WHERE `skill_id` = '1299';
UPDATE `skill_trees` SET `name` = '使魔治療術' WHERE `skill_id` = '1300';
UPDATE `skill_trees` SET `name` = '使魔祝福' WHERE `skill_id` = '1301';
UPDATE `skill_trees` SET `name` = '野性魔力' WHERE `skill_id` = '1303';
UPDATE `skill_trees` SET `name` = '伊娃之盾' WHERE `skill_id` = '1304';
UPDATE `skill_trees` SET `name` = '帕格立歐敬意' WHERE `skill_id` = '1305';
UPDATE `skill_trees` SET `name` = '生命祭禮' WHERE `skill_id` = '1306';
UPDATE `skill_trees` SET `name` = '祈禱' WHERE `skill_id` = '1307';
UPDATE `skill_trees` SET `name` = '掠奪頌歌' WHERE `skill_id` = '1308';
UPDATE `skill_trees` SET `name` = '獵鷹頌歌' WHERE `skill_id` = '1309';
UPDATE `skill_trees` SET `name` = '嗜血頌歌' WHERE `skill_id` = '1310';
UPDATE `skill_trees` SET `name` = '聖化之體' WHERE `skill_id` = '1311';
UPDATE `skill_trees` SET `name` = '釣魚' WHERE `skill_id` = '1312';
UPDATE `skill_trees` SET `name` = '拉線' WHERE `skill_id` = '1313';
UPDATE `skill_trees` SET `name` = '放線' WHERE `skill_id` = '1314';
UPDATE `skill_trees` SET `name` = '精通釣魚' WHERE `skill_id` = '1315';
UPDATE `skill_trees` SET `name` = '精通釣魚-C級' WHERE `skill_id` = '1316';
UPDATE `skill_trees` SET `name` = '精通釣魚-B級' WHERE `skill_id` = '1317';
UPDATE `skill_trees` SET `name` = '精通釣魚-A級' WHERE `skill_id` = '1318';
UPDATE `skill_trees` SET `name` = '精通釣魚-S級' WHERE `skill_id` = '1319';
UPDATE `skill_trees` SET `name` = '製作一般道具' WHERE `skill_id` = '1320';
UPDATE `skill_trees` SET `name` = '矮人工藝' WHERE `skill_id` = '1321';
UPDATE `skill_trees` SET `name` = '一般工藝' WHERE `skill_id` = '1322';
UPDATE `skill_trees` SET `name` = '貴族的祝福' WHERE `skill_id` = '1323';
UPDATE `skill_trees` SET `name` = '召喚鬥志藥水' WHERE `skill_id` = '1324';
UPDATE `skill_trees` SET `name` = '貴族的強運' WHERE `skill_id` = '1325';
UPDATE `skill_trees` SET `name` = '貴族的和聲' WHERE `skill_id` = '1326';
UPDATE `skill_trees` SET `name` = '貴族的共鳴' WHERE `skill_id` = '1327';
UPDATE `skill_trees` SET `name` = '召喚暴風晶體群' WHERE `skill_id` = '1328';
UPDATE `skill_trees` SET `name` = '召喚水液晶體群' WHERE `skill_id` = '1329';
UPDATE `skill_trees` SET `name` = '召喚干擾晶體群' WHERE `skill_id` = '1330';
UPDATE `skill_trees` SET `name` = '召喚皇后貓' WHERE `skill_id` = '1331';
UPDATE `skill_trees` SET `name` = '召喚天使獨角獸' WHERE `skill_id` = '1332';
UPDATE `skill_trees` SET `name` = '召喚夜靈' WHERE `skill_id` = '1333';
UPDATE `skill_trees` SET `name` = '召喚受詛咒者' WHERE `skill_id` = '1334';
UPDATE `skill_trees` SET `name` = '生命之衡' WHERE `skill_id` = '1335';
UPDATE `skill_trees` SET `name` = '末日詛咒' WHERE `skill_id` = '1336';
UPDATE `skill_trees` SET `name` = '深淵詛咒' WHERE `skill_id` = '1337';
UPDATE `skill_trees` SET `name` = '混沌的奧祕' WHERE `skill_id` = '1338';
UPDATE `skill_trees` SET `name` = '炎之旋流' WHERE `skill_id` = '1339';
UPDATE `skill_trees` SET `name` = '冰之旋流' WHERE `skill_id` = '1340';
UPDATE `skill_trees` SET `name` = '風之旋流' WHERE `skill_id` = '1341';
UPDATE `skill_trees` SET `name` = '光之旋流' WHERE `skill_id` = '1342';
UPDATE `skill_trees` SET `name` = '闇之旋流' WHERE `skill_id` = '1343';
UPDATE `skill_trees` SET `name` = '群體敏捷禁制咒' WHERE `skill_id` = '1344';
UPDATE `skill_trees` SET `name` = '群體魔力禁制咒' WHERE `skill_id` = '1345';
UPDATE `skill_trees` SET `name` = '鬥者使魔' WHERE `skill_id` = '1346';
UPDATE `skill_trees` SET `name` = '巫師使魔' WHERE `skill_id` = '1347';
UPDATE `skill_trees` SET `name` = '殺手使魔' WHERE `skill_id` = '1348';
UPDATE `skill_trees` SET `name` = '終極使魔' WHERE `skill_id` = '1349';
UPDATE `skill_trees` SET `name` = '敏捷禁制咒' WHERE `skill_id` = '1350';
UPDATE `skill_trees` SET `name` = '魔力禁制咒' WHERE `skill_id` = '1351';
UPDATE `skill_trees` SET `name` = '元素加護' WHERE `skill_id` = '1352';
UPDATE `skill_trees` SET `name` = '神聖加護' WHERE `skill_id` = '1353';
UPDATE `skill_trees` SET `name` = '奧祕加護' WHERE `skill_id` = '1354';
UPDATE `skill_trees` SET `name` = '水之預言' WHERE `skill_id` = '1355';
UPDATE `skill_trees` SET `name` = '火之預言' WHERE `skill_id` = '1356';
UPDATE `skill_trees` SET `name` = '風之預言' WHERE `skill_id` = '1357';
UPDATE `skill_trees` SET `name` = '防禦禁制結界' WHERE `skill_id` = '1358';
UPDATE `skill_trees` SET `name` = '速度禁制結界' WHERE `skill_id` = '1359';
UPDATE `skill_trees` SET `name` = '群體防禦禁制結界' WHERE `skill_id` = '1360';
UPDATE `skill_trees` SET `name` = '群體速度禁制結界' WHERE `skill_id` = '1361';
UPDATE `skill_trees` SET `name` = '聖靈頌歌' WHERE `skill_id` = '1362';
UPDATE `skill_trees` SET `name` = '凱旋頌歌' WHERE `skill_id` = '1363';
UPDATE `skill_trees` SET `name` = '帕格立歐凝視' WHERE `skill_id` = '1364';
UPDATE `skill_trees` SET `name` = '帕格立歐之魂' WHERE `skill_id` = '1365';
UPDATE `skill_trees` SET `name` = '絕望封印' WHERE `skill_id` = '1366';
UPDATE `skill_trees` SET `name` = '疫病封印' WHERE `skill_id` = '1367';
UPDATE `skill_trees` SET `name` = '擴充矮人工藝' WHERE `skill_id` = '1368';
UPDATE `skill_trees` SET `name` = '擴充一般工藝' WHERE `skill_id` = '1369';
UPDATE `skill_trees` SET `name` = '擴充個人商店' WHERE `skill_id` = '1370';
UPDATE `skill_trees` SET `name` = '擴充倉庫' WHERE `skill_id` = '1371';
UPDATE `skill_trees` SET `name` = '擴充包袱' WHERE `skill_id` = '1372';
UPDATE `skill_trees` SET `name` = '精通座龍騎術' WHERE `skill_id` = '1373';
UPDATE `skill_trees` SET `name` = '英雄的勇氣' WHERE `skill_id` = '1374';
UPDATE `skill_trees` SET `name` = '英雄的威嚴' WHERE `skill_id` = '1375';
UPDATE `skill_trees` SET `name` = '英雄的恐怖' WHERE `skill_id` = '1376';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '1377';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '1378';
UPDATE `skill_trees` SET `name` = '' WHERE `skill_id` = '1379';
UPDATE `skill_trees` SET `name` = '背叛' WHERE `skill_id` = '1380';
UPDATE `skill_trees` SET `name` = '恐懼結界' WHERE `skill_id` = '1381';
UPDATE `skill_trees` SET `name` = '暗影詛咒結界' WHERE `skill_id` = '1382';
UPDATE `skill_trees` SET `name` = '火之陷落結界' WHERE `skill_id` = '1383';
UPDATE `skill_trees` SET `name` = '水之陷落結界' WHERE `skill_id` = '1384';
UPDATE `skill_trees` SET `name` = '風之陷落結界' WHERE `skill_id` = '1385';
UPDATE `skill_trees` SET `name` = '思緒紊亂' WHERE `skill_id` = '1386';
UPDATE `skill_trees` SET `name` = '召喚受詛咒之骨' WHERE `skill_id` = '1387';
UPDATE `skill_trees` SET `name` = '高級力量強化' WHERE `skill_id` = '1388';
UPDATE `skill_trees` SET `name` = '高級保護盾' WHERE `skill_id` = '1389';
UPDATE `skill_trees` SET `name` = '戰爭頌歌' WHERE `skill_id` = '1390';
UPDATE `skill_trees` SET `name` = '大地頌歌' WHERE `skill_id` = '1391';
UPDATE `skill_trees` SET `name` = '聖之防護' WHERE `skill_id` = '1392';
UPDATE `skill_trees` SET `name` = '暗之防護' WHERE `skill_id` = '1393';
UPDATE `skill_trees` SET `name` = '失神術' WHERE `skill_id` = '1394';
UPDATE `skill_trees` SET `name` = '使魔消除' WHERE `skill_id` = '1395';
UPDATE `skill_trees` SET `name` = '魔力反噬' WHERE `skill_id` = '1396';
UPDATE `skill_trees` SET `name` = '澄澈思緒' WHERE `skill_id` = '1397';
UPDATE `skill_trees` SET `name` = '魔力燃燒' WHERE `skill_id` = '1398';
UPDATE `skill_trees` SET `name` = '魔力風暴' WHERE `skill_id` = '1399';
UPDATE `skill_trees` SET `name` = '破邪法' WHERE `skill_id` = '1400';
UPDATE `skill_trees` SET `name` = '極大治癒術' WHERE `skill_id` = '1401';
UPDATE `skill_trees` SET `name` = '極大集體治癒術' WHERE `skill_id` = '1402';
UPDATE `skill_trees` SET `name` = '召喚戰友' WHERE `skill_id` = '1403';
UPDATE `skill_trees` SET `name` = '招來咒言' WHERE `skill_id` = '1404';
UPDATE `skill_trees` SET `name` = '神威加持' WHERE `skill_id` = '1405';
UPDATE `skill_trees` SET `name` = '召喚國王貓' WHERE `skill_id` = '1406';
UPDATE `skill_trees` SET `name` = '召喚輝煌獨角獸' WHERE `skill_id` = '1407';
UPDATE `skill_trees` SET `name` = '召喚幽冥之主' WHERE `skill_id` = '1408';
UPDATE `skill_trees` SET `name` = '淨罪' WHERE `skill_id` = '1409';
UPDATE `skill_trees` SET `name` = '救贖' WHERE `skill_id` = '1410';
UPDATE `skill_trees` SET `name` = '祕術免疫' WHERE `skill_id` = '1411';
UPDATE `skill_trees` SET `name` = '咒文偏移' WHERE `skill_id` = '1412';
UPDATE `skill_trees` SET `name` = '輝煌頌歌' WHERE `skill_id` = '1413';
UPDATE `skill_trees` SET `name` = '帕格立歐必勝' WHERE `skill_id` = '1414';
UPDATE `skill_trees` SET `name` = '帕格立歐聖徽' WHERE `skill_id` = '1415';
UPDATE `skill_trees` SET `name` = '帕格立歐奮戰' WHERE `skill_id` = '1416';
UPDATE `skill_trees` SET `name` = '靈氣閃光' WHERE `skill_id` = '1417';
UPDATE `skill_trees` SET `name` = '天國聖盾' WHERE `skill_id` = '1418';
UPDATE `skill_trees` SET `name` = '魔法陣‧爆炎' WHERE `skill_id` = '1419';
UPDATE `skill_trees` SET `name` = '魔法陣‧烈風' WHERE `skill_id` = '1420';
UPDATE `skill_trees` SET `name` = '魔法陣‧海嘯' WHERE `skill_id` = '1421';
UPDATE `skill_trees` SET `name` = '魔法陣‧末日' WHERE `skill_id` = '1422';
UPDATE `skill_trees` SET `name` = '魔法陣‧煉獄' WHERE `skill_id` = '1423';
UPDATE `skill_trees` SET `name` = '魔法陣‧次元裂縫' WHERE `skill_id` = '1424';
UPDATE `skill_trees` SET `name` = '魔法陣‧純淨' WHERE `skill_id` = '1425';
UPDATE `skill_trees` SET `name` = '魔法陣‧奇蹟' WHERE `skill_id` = '1426';
UPDATE `skill_trees` SET `name` = '魔法陣‧不滅之火' WHERE `skill_id` = '1427';
UPDATE `skill_trees` SET `name` = '魔法陣‧魔力泉源' WHERE `skill_id` = '1428';
UPDATE `skill_trees` SET `name` = '門扉頌歌' WHERE `skill_id` = '1429';
UPDATE `skill_trees` SET `name` = '默禱' WHERE `skill_id` = '1430';
UPDATE `skill_trees` SET `name` = '墮落之箭' WHERE `skill_id` = '1431';
UPDATE `skill_trees` SET `name` = '力量加持' WHERE `skill_id` = '1432';
UPDATE `skill_trees` SET `name` = '深淵赤焰' WHERE `skill_id` = '1433';
UPDATE `skill_trees` SET `name` = '黑暗爆裂' WHERE `skill_id` = '1434';
UPDATE `skill_trees` SET `name` = '死亡印記' WHERE `skill_id` = '1435';
UPDATE `skill_trees` SET `name` = '劇痛靈魂' WHERE `skill_id` = '1436';
UPDATE `skill_trees` SET `name` = '黑暗火焰' WHERE `skill_id` = '1437';
UPDATE `skill_trees` SET `name` = '湮滅之輪' WHERE `skill_id` = '1438';
UPDATE `skill_trees` SET `name` = '神威詛咒' WHERE `skill_id` = '1439';
UPDATE `skill_trees` SET `name` = '神威竊取' WHERE `skill_id` = '1440';
UPDATE `skill_trees` SET `name` = '轉魂催化' WHERE `skill_id` = '1441';
UPDATE `skill_trees` SET `name` = '幽暗保護' WHERE `skill_id` = '1442';
UPDATE `skill_trees` SET `name` = '黑暗武器' WHERE `skill_id` = '1443';
UPDATE `skill_trees` SET `name` = '闇天使的驕傲' WHERE `skill_id` = '1444';
UPDATE `skill_trees` SET `name` = '臣服邪惡' WHERE `skill_id` = '1445';
UPDATE `skill_trees` SET `name` = '縫影' WHERE `skill_id` = '1446';
UPDATE `skill_trees` SET `name` = '絕音' WHERE `skill_id` = '1447';
UPDATE `skill_trees` SET `name` = '閃逝' WHERE `skill_id` = '1448';
UPDATE `skill_trees` SET `name` = '靈魂轉移' WHERE `skill_id` = '1449';
UPDATE `skill_trees` SET `name` = '連鎖閃電' WHERE `skill_id` = '1450';
UPDATE `skill_trees` SET `name` = '炎旋爆破' WHERE `skill_id` = '1451';
UPDATE `skill_trees` SET `name` = '火焰計數' WHERE `skill_id` = '1452';
UPDATE `skill_trees` SET `name` = '冰旋巨鎚' WHERE `skill_id` = '1453';
UPDATE `skill_trees` SET `name` = '冰晶' WHERE `skill_id` = '1454';
UPDATE `skill_trees` SET `name` = '冰之霸權' WHERE `skill_id` = '1455';
UPDATE `skill_trees` SET `name` = '風旋重擊' WHERE `skill_id` = '1456';
UPDATE `skill_trees` SET `name` = '回音魔力催化' WHERE `skill_id` = '1457';
UPDATE `skill_trees` SET `name` = '風之霸權' WHERE `skill_id` = '1458';
UPDATE `skill_trees` SET `name` = '神聖之力' WHERE `skill_id` = '1459';
UPDATE `skill_trees` SET `name` = '魔力回復' WHERE `skill_id` = '1460';
UPDATE `skill_trees` SET `name` = '保護頌歌' WHERE `skill_id` = '1461';
UPDATE `skill_trees` SET `name` = '阻絕封印' WHERE `skill_id` = '1462';
UPDATE `skill_trees` SET `name` = '火焰武器' WHERE `skill_id` = '1463';
UPDATE `skill_trees` SET `name` = '冰凍武器' WHERE `skill_id` = '1464';
UPDATE `skill_trees` SET `name` = '狂風武器' WHERE `skill_id` = '1465';
UPDATE `skill_trees` SET `name` = '大地武器' WHERE `skill_id` = '1466';
UPDATE `skill_trees` SET `name` = '隕石術' WHERE `skill_id` = '1467';
UPDATE `skill_trees` SET `name` = '墜星術' WHERE `skill_id` = '1468';
UPDATE `skill_trees` SET `name` = '雷歐波爾德' WHERE `skill_id` = '1469';
UPDATE `skill_trees` SET `name` = '弗萊格拉克' WHERE `skill_id` = '1470';
UPDATE `skill_trees` SET `name` = '死光' WHERE `skill_id` = '1471';
UPDATE `skill_trees` SET `name` = '靈魂抽取' WHERE `skill_id` = '1472';
UPDATE `skill_trees` SET `name` = '轉換武器' WHERE `skill_id` = '1473';
UPDATE `skill_trees` SET `name` = '深淵的力量' WHERE `skill_id` = '1474';
UPDATE `skill_trees` SET `name` = '印記抹除' WHERE `skill_id` = '1475';
UPDATE `skill_trees` SET `name` = '摧毀直覺' WHERE `skill_id` = '1476';
UPDATE `skill_trees` SET `name` = '吸血鬼動念' WHERE `skill_id` = '1477';
UPDATE `skill_trees` SET `name` = '保護直覺' WHERE `skill_id` = '1478';
UPDATE `skill_trees` SET `name` = '魔法動念' WHERE `skill_id` = '1479';
UPDATE `skill_trees` SET `name` = '靈魂和諧' WHERE `skill_id` = '1480';
UPDATE `skill_trees` SET `name` = '忘卻' WHERE `skill_id` = '1481';
UPDATE `skill_trees` SET `name` = '體質弱化' WHERE `skill_id` = '1482';
UPDATE `skill_trees` SET `name` = '皮膚破損' WHERE `skill_id` = '1483';
UPDATE `skill_trees` SET `name` = '虛弱' WHERE `skill_id` = '1484';
UPDATE `skill_trees` SET `name` = '惡意' WHERE `skill_id` = '1485';
UPDATE `skill_trees` SET `name` = '心靈耗竭' WHERE `skill_id` = '1486';
UPDATE `skill_trees` SET `name` = '修復術' WHERE `skill_id` = '1487';
UPDATE `skill_trees` SET `name` = '壓縮修復術' WHERE `skill_id` = '1488';
UPDATE `skill_trees` SET `name` = '召喚士能力-屬性抵抗' WHERE `skill_id` = '1489';
UPDATE `skill_trees` SET `name` = '牧師能力-治療' WHERE `skill_id` = '1490';
UPDATE `skill_trees` SET `name` = '召喚士能力-魂靈' WHERE `skill_id` = '1491';
UPDATE `skill_trees` SET `name` = '火焰裝甲' WHERE `skill_id` = '1492';
UPDATE `skill_trees` SET `name` = '寒霜裝甲' WHERE `skill_id` = '1493';
UPDATE `skill_trees` SET `name` = '風暴裝甲' WHERE `skill_id` = '1494';
UPDATE `skill_trees` SET `name` = '吸血迷霧' WHERE `skill_id` = '1495';
UPDATE `skill_trees` SET `name` = '使魔屏障' WHERE `skill_id` = '1496';
UPDATE `skill_trees` SET `name` = '極度忠誠' WHERE `skill_id` = '1497';
UPDATE `skill_trees` SET `name` = '相互呼應' WHERE `skill_id` = '1498';
UPDATE `skill_trees` SET `name` = '提升戰鬥' WHERE `skill_id` = '1499';
UPDATE `skill_trees` SET `name` = '提升魔法' WHERE `skill_id` = '1500';
UPDATE `skill_trees` SET `name` = '提升狀態' WHERE `skill_id` = '1501';
UPDATE `skill_trees` SET `name` = '提升致命攻擊' WHERE `skill_id` = '1502';
UPDATE `skill_trees` SET `name` = '提升盾防禦' WHERE `skill_id` = '1503';
UPDATE `skill_trees` SET `name` = '提升行動力' WHERE `skill_id` = '1504';
UPDATE `skill_trees` SET `name` = '崇高自我獻祭' WHERE `skill_id` = '1505';
UPDATE `skill_trees` SET `name` = '伊娃祝福' WHERE `skill_id` = '1506';
UPDATE `skill_trees` SET `name` = '吸血鬼之王' WHERE `skill_id` = '1507';
UPDATE `skill_trees` SET `name` = '霸權纏繞' WHERE `skill_id` = '1508';
UPDATE `skill_trees` SET `name` = '極限封印' WHERE `skill_id` = '1509';
UPDATE `skill_trees` SET `name` = '靈魂淨罪' WHERE `skill_id` = '1510';
UPDATE `skill_trees` SET `name` = '生命流動詛咒' WHERE `skill_id` = '1511';
UPDATE `skill_trees` SET `name` = '魂之旋流' WHERE `skill_id` = '1512';
UPDATE `skill_trees` SET `name` = '魂旋破滅' WHERE `skill_id` = '1513';
UPDATE `skill_trees` SET `name` = '靈魂屏障' WHERE `skill_id` = '1514';
UPDATE `skill_trees` SET `name` = '強雷屏障' WHERE `skill_id` = '1515';
UPDATE `skill_trees` SET `name` = '魂靈強擊' WHERE `skill_id` = '1516';
UPDATE `skill_trees` SET `name` = '戰鬥頌歌' WHERE `skill_id` = '1517';
UPDATE `skill_trees` SET `name` = '致命攻擊頌歌' WHERE `skill_id` = '1518';
UPDATE `skill_trees` SET `name` = '血之覺醒頌歌' WHERE `skill_id` = '1519';
UPDATE `skill_trees` SET `name` = '審問者' WHERE `skill_id` = '1520';
UPDATE `skill_trees` SET `name` = '審問者' WHERE `skill_id` = '1521';
UPDATE `skill_trees` SET `name` = '審問者' WHERE `skill_id` = '1522';
UPDATE `skill_trees` SET `name` = '神聖懲罰' WHERE `skill_id` = '1523';
UPDATE `skill_trees` SET `name` = '聖之陷落' WHERE `skill_id` = '1524';
UPDATE `skill_trees` SET `name` = '神聖詛咒' WHERE `skill_id` = '1525';
UPDATE `skill_trees` SET `name` = '竊取魔力' WHERE `skill_id` = '1526';
UPDATE `skill_trees` SET `name` = '專業施法' WHERE `skill_id` = '1527';
UPDATE `skill_trees` SET `name` = '神聖閃光' WHERE `skill_id` = '1528';
UPDATE `skill_trees` SET `name` = '捕魂網' WHERE `skill_id` = '1529';
UPDATE `skill_trees` SET `name` = '死亡之刺' WHERE `skill_id` = '1530';
UPDATE `skill_trees` SET `name` = '神佑之血' WHERE `skill_id` = '1531';

/***** Done by vdmyagami！ *****/